// PreToolUse (Edit|Write|MultiEdit|NotebookEdit): block edits to protected paths.
// - mockup-clone/ is the read-only reference copy (ADR-002)
// - .env files hold secrets and are never edited by the agent
'use strict';
const { readInput, projectDir, isUnder, rel, deny, path } = require('./_lib');

const input = readInput();
const file = input.tool_input && (input.tool_input.file_path || input.tool_input.notebook_path);
if (!file) process.exit(0);

const root = projectDir(input);
const r = rel(root, file);
const base = path.basename(file);

if (isUnder(root, file, 'mockup-clone')) {
  deny('PreToolUse', `mockup-clone/ is the read-only reference copy (ADR-002). Refused to edit ${r}. Make the change in mockup-v2/ or the real build instead.`);
  process.exit(0);
}

if (/^\.env(\..+)?$/.test(base) && !/\.(example|template|sample)$/.test(base)) {
  deny('PreToolUse', `${r} holds secrets. The agent never edits .env files; tell the user what to set instead.`);
  process.exit(0);
}

if (/^coingreeks-v2(\.local)?\.html$/.test(base) && isUnder(root, file, 'mockup-v2')) {
  deny('PreToolUse', `${r} is generated by mockup-v2/assemble.js. Edit the source under parts/, parts-src/, src-trd/, chrome-src/, public-src/, adm-src/ or _analytics-src/ and rebuild.`);
  process.exit(0);
}

process.exit(0);
