#!/usr/bin/env node
// Generates src/tokens.css and src/tokens.ts from the v2 mock's design-system block (ADR-003).
// Source of truth: mockup-v2/shell-head.html, the `:root{...}` (light) and `html.dark{...}` (dark) rules.
// Usage: `pnpm gen:tokens` (writes into src/) or `node scripts/gen-tokens.mjs --out <dir>` (used by the drift test).
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
export const SOURCE = resolve(here, "../../../mockup-v2/shell-head.html");
const HEADER =
  "/* GENERATED by scripts/gen-tokens.mjs from mockup-v2/shell-head.html. Do not edit; run `pnpm gen:tokens`. */";

/** Extract the declaration body of the first rule whose selector list is exactly `selector`. */
function ruleBody(css, selector) {
  const re = new RegExp(`(?:^|[\\n}])${selector.replace(/[.]/g, "\\.")}\\{([^}]*)\\}`);
  const m = re.exec(css);
  if (!m) throw new Error(`gen-tokens: rule "${selector}{...}" not found in ${SOURCE}`);
  return m[1];
}

/** Parse `--name:value;...` into an ordered list of [name, value]; non-custom properties are kept separately. */
function parseDeclarations(body) {
  const tokens = [];
  const plain = [];
  // Split on ';' that are not inside quotes.
  const parts = body.match(/(?:[^;"]+|"[^"]*")+/g) ?? [];
  for (const raw of parts) {
    const decl = raw.trim();
    if (!decl) continue;
    const idx = decl.indexOf(":");
    const prop = decl.slice(0, idx).trim();
    const value = decl.slice(idx + 1).trim();
    if (prop.startsWith("--")) tokens.push([prop.slice(2), normalizeValue(value)]);
    else plain.push([prop, normalizeValue(value)]);
  }
  return { tokens, plain };
}

const HSL_TRIPLE = /^\d+(?:\.\d+)? \d+(?:\.\d+)?% \d+(?:\.\d+)?%$/;

/** Prettier-stable value formatting (semantically identical): leading zero on decimals, space after commas. */
function normalizeValue(value) {
  return value.replace(/(^|[\s(,])\.(\d)/g, "$10.$2").replace(/,(?=\S)/g, ", ");
}

export function generate(source = SOURCE) {
  const css = readFileSync(source, "utf8");
  const light = parseDeclarations(ruleBody(css, ":root"));
  const dark = parseDeclarations(ruleBody(css, "html.dark"));

  const lightNames = light.tokens.map(([n]) => n);
  const darkNames = new Set(dark.tokens.map(([n]) => n));
  const colorNames = light.tokens.filter(([, v]) => HSL_TRIPLE.test(v)).map(([n]) => n);
  const fontNames = light.tokens.filter(([n]) => n.startsWith("font-")).map(([n]) => n);
  const otherNames = lightNames.filter((n) => !colorNames.includes(n) && !fontNames.includes(n));

  for (const n of darkNames) {
    if (!lightNames.includes(n)) throw new Error(`gen-tokens: dark defines "--${n}" which light does not`);
  }
  for (const n of colorNames) {
    if (!darkNames.has(n)) throw new Error(`gen-tokens: colour token "--${n}" has no dark value`);
  }

  const decls = (list) => list.map(([n, v]) => `  --${n}: ${v};`).join("\n");
  const plain = (list) => list.map(([p, v]) => `  ${p}: ${v};`).join("\n");
  const darkBlock = [decls(dark.tokens), plain(dark.plain)].filter(Boolean).join("\n");

  const tokensCss = `${HEADER}
/* HapieCoin "Obsidian Desk" tokens: dark-first with a first-class light theme (ADR-003).
   Colours are HSL triples; consume as hsl(var(--name)) or via the Tailwind theme in theme.css. */
:root {
${decls(light.tokens)}
${plain(light.plain)}
}
.dark {
${darkBlock}
}
@media (prefers-color-scheme: dark) {
  :root:not(.light) {
${darkBlock.replace(/^/gm, "  ")}
  }
}
`;

  // Prettier's layout (printWidth 110): one line when it fits, otherwise one element per line,
  // so `prettier --check` never rewrites the generated file.
  const PRINT_WIDTH = 110;
  const tuple = (name, names) => {
    const oneLine = `export const ${name} = [${names.map((n) => JSON.stringify(n)).join(", ")}] as const;`;
    if (oneLine.length <= PRINT_WIDTH) return oneLine;
    return `export const ${name} = [\n${names.map((n) => `  ${JSON.stringify(n)},`).join("\n")}\n] as const;`;
  };
  const tokensTs = `${HEADER.replace("/*", "//").replace(" */", "")}
/** Colour tokens (HSL triples) that have both a light and a dark value. */
${tuple("colorTokens", colorNames)}
/** Font-family tokens (same in both themes). */
${tuple("fontTokens", fontNames)}
/** Remaining tokens (radius, etc.), same in both themes. */
${tuple("otherTokens", otherNames)}
/** Every custom property name declared on \`:root\`, in source order. */
${tuple("tokens", lightNames)}

export type ColorToken = (typeof colorTokens)[number];
export type FontToken = (typeof fontTokens)[number];
export type OtherToken = (typeof otherTokens)[number];
export type Token = (typeof tokens)[number];

/** \`hsl(var(--token))\`, optionally with an alpha such as \`0.2\` or \`"22%"\`. */
export function hsl(token: ColorToken, alpha?: number | string): string {
  return alpha === undefined ? \`hsl(var(--\${token}))\` : \`hsl(var(--\${token}) / \${alpha})\`;
}

/** \`var(--token)\` for non-colour tokens (fonts, radius). */
export function cssVar(token: Token): string {
  return \`var(--\${token})\`;
}
`;

  return { tokensCss, tokensTs, colorNames, fontNames, otherNames };
}

export function writeTokens(outDir) {
  const { tokensCss, tokensTs } = generate();
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, "tokens.css"), tokensCss);
  writeFileSync(join(outDir, "tokens.ts"), tokensTs);
  return { css: join(outDir, "tokens.css"), ts: join(outDir, "tokens.ts") };
}

const invokedDirectly = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (invokedDirectly) {
  const outFlag = process.argv.indexOf("--out");
  const outDir =
    outFlag > -1 && process.argv[outFlag + 1] ? resolve(process.argv[outFlag + 1]) : resolve(here, "../src");
  const files = writeTokens(outDir);
  process.stdout.write(`gen-tokens: wrote ${files.css} and ${files.ts}\n`);
}
