// GENERATED by scripts/gen-tokens.mjs from mockup-v2/shell-head.html. Do not edit; run `pnpm gen:tokens`.
/** Colour tokens (HSL triples) that have both a light and a dark value. */
export const colorTokens = [
  "background",
  "foreground",
  "card",
  "card-foreground",
  "popover",
  "popover-foreground",
  "primary",
  "primary-foreground",
  "secondary",
  "secondary-foreground",
  "muted",
  "muted-foreground",
  "accent",
  "accent-foreground",
  "destructive",
  "destructive-foreground",
  "border",
  "input",
  "ring",
  "profit",
  "loss",
  "warning",
  "warning-bg",
  "info",
  "info-bg",
  "buy",
  "sell",
  "buy-bg",
  "sell-bg",
  "surface-1",
  "surface-2",
  "surface-3",
  "header-bg",
  "header-fg",
  "sidebar-background",
  "sidebar-foreground",
  "sidebar-primary",
  "sidebar-accent",
  "sidebar-border",
  "spot",
  "curve",
] as const;
/** Font-family tokens (same in both themes). */
export const fontTokens = ["font-display", "font-body", "font-mono"] as const;
/** Remaining tokens (radius, etc.), same in both themes. */
export const otherTokens = ["radius"] as const;
/** Every custom property name declared on `:root`, in source order. */
export const tokens = [
  "background",
  "foreground",
  "card",
  "card-foreground",
  "popover",
  "popover-foreground",
  "primary",
  "primary-foreground",
  "secondary",
  "secondary-foreground",
  "muted",
  "muted-foreground",
  "accent",
  "accent-foreground",
  "destructive",
  "destructive-foreground",
  "border",
  "input",
  "ring",
  "radius",
  "profit",
  "loss",
  "warning",
  "warning-bg",
  "info",
  "info-bg",
  "buy",
  "sell",
  "buy-bg",
  "sell-bg",
  "surface-1",
  "surface-2",
  "surface-3",
  "header-bg",
  "header-fg",
  "sidebar-background",
  "sidebar-foreground",
  "sidebar-primary",
  "sidebar-accent",
  "sidebar-border",
  "spot",
  "curve",
  "font-display",
  "font-body",
  "font-mono",
] as const;

export type ColorToken = (typeof colorTokens)[number];
export type FontToken = (typeof fontTokens)[number];
export type OtherToken = (typeof otherTokens)[number];
export type Token = (typeof tokens)[number];

/** `hsl(var(--token))`, optionally with an alpha such as `0.2` or `"22%"`. */
export function hsl(token: ColorToken, alpha?: number | string): string {
  return alpha === undefined ? `hsl(var(--${token}))` : `hsl(var(--${token}) / ${alpha})`;
}

/** `var(--token)` for non-colour tokens (fonts, radius). */
export function cssVar(token: Token): string {
  return `var(--${token})`;
}
