/* ===== HapieCoin clone · core runtime: mock data, pricing, router, modal, toast, theme, chrome ===== */
(function () {
  const CG = (window.CG = window.CG || {});
  // ---------- deterministic pseudo-random ----------
  function rng(seed) { let s = seed >>> 0 || 1; return function () { s = (s * 1664525 + 1013904223) >>> 0; return s / 4294967296; }; }
  CG.rng = rng;
  CG.series = function (n, base, vol, seed, drift) { const r = rng(seed); const out = []; let v = base; for (let i = 0; i < n; i++) { v = v * (1 + (r() - 0.5) * vol + (drift || 0)); out.push(v); } return out; };
  // ---------- formatting ----------
  const F = (CG.fmt = {});
  F.num = (n, d = 2) => (n == null || isNaN(n) ? '—' : Number(n).toLocaleString('en-US', { minimumFractionDigits: d, maximumFractionDigits: d }));
  F.int = (n) => F.num(n, 0);
  F.usd = (n, d = 2) => (n == null || isNaN(n) ? '—' : (n < 0 ? '-' : '') + '$' + F.num(Math.abs(n), d));
  F.inr = (n, d = 0) => (n == null || isNaN(n) ? '—' : (n < 0 ? '-' : '') + '₹' + Number(Math.abs(n)).toLocaleString('en-IN', { minimumFractionDigits: d, maximumFractionDigits: d }));
  F.money = (n, d = 2) => (CG.state.currency === 'INR' ? F.inr(n * CG.state.conversionRate, d) : F.usd(n, d));
  F.signed = (n, d = 2) => (n == null || isNaN(n) ? '—' : (n >= 0 ? '+' : '-') + F.num(Math.abs(n), d));
  F.signedMoney = (n, d = 2) => (n == null || isNaN(n) ? '—' : (n >= 0 ? '+' : '-') + F.money(Math.abs(n), d));
  F.pct = (n, d = 2) => (n == null || isNaN(n) ? '—' : (n >= 0 ? '+' : '') + F.num(n, d) + '%');
  F.pct0 = (n, d = 1) => (n == null || isNaN(n) ? '—' : F.num(n, d) + '%');
  F.compact = (n) => { if (n == null || isNaN(n)) return '—'; const a = Math.abs(n); const s = n < 0 ? '-' : ''; if (a >= 1e12) return s + (a / 1e12).toFixed(2) + 'T'; if (a >= 1e9) return s + (a / 1e9).toFixed(2) + 'B'; if (a >= 1e6) return s + (a / 1e6).toFixed(2) + 'M'; if (a >= 1e3) return s + (a / 1e3).toFixed(2) + 'K'; return s + a.toFixed(a < 10 ? 2 : 0); };
  F.usdCompact = (n) => (n == null || isNaN(n) ? '—' : (n < 0 ? '-$' : '$') + F.compact(Math.abs(n)));
  F.date = (d, opts) => { const x = d instanceof Date ? d : new Date(d); return x.toLocaleDateString('en-US', opts || { day: '2-digit', month: 'short', year: 'numeric' }); };
  F.dateIN = (d) => { const x = d instanceof Date ? d : new Date(d); return x.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }); };
  F.time = (d) => { const x = d instanceof Date ? d : new Date(d); return x.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }); };
  F.expiryLabel = (code) => code; // e.g. 25SEP26
  F.expiryDate = (code) => { const m = /^(\d{2})([A-Z]{3})(\d{2})$/.exec(code); if (!m) return new Date(code); const mon = ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'].indexOf(m[2]); return new Date(Date.UTC(2000 + +m[3], mon, +m[1], 12, 0, 0)); };
  F.dte = (code) => Math.max(0, Math.round((F.expiryDate(code) - CG.NOW) / 86400000));
  // ---------- pricing (Black-76, r = 0) ----------
  const P = (CG.pricing = {});
  function N(x) { const t = 1 / (1 + 0.2316419 * Math.abs(x)); const d = 0.3989423 * Math.exp(-x * x / 2); const p = d * t * (0.3193815 + t * (-0.3565638 + t * (1.781478 + t * (-1.821256 + t * 1.330274)))); return x > 0 ? 1 - p : p; }
  const pdf = (x) => Math.exp(-x * x / 2) / Math.sqrt(2 * Math.PI);
  P.N = N;
  P.price = function (F0, K, T, s, call) { if (T <= 0 || s <= 0) return Math.max(call ? F0 - K : K - F0, 0); const v = s * Math.sqrt(T); const d1 = (Math.log(F0 / K) + 0.5 * v * v) / v, d2 = d1 - v; return call ? F0 * N(d1) - K * N(d2) : K * N(-d2) - F0 * N(-d1); };
  P.greeks = function (F0, K, T, s, call) { if (T <= 0 || s <= 0) { const itm = call ? F0 > K : F0 < K; return { delta: itm ? (call ? 1 : -1) : 0, gamma: 0, theta: 0, vega: 0, rho: 0 }; } const v = s * Math.sqrt(T); const d1 = (Math.log(F0 / K) + 0.5 * v * v) / v; const delta = call ? N(d1) : N(d1) - 1; const gamma = pdf(d1) / (F0 * v); const vega = F0 * pdf(d1) * Math.sqrt(T) / 100; const theta = -(F0 * pdf(d1) * s) / (2 * Math.sqrt(T)) / 365; return { delta, gamma, vega, theta, rho: 0 }; };
  P.smile = function (K, F0, base) { const m = Math.log(K / F0); return (base || 0.424) + 0.9 * m * m - 0.12 * m; };
  P.iv = function (target, F0, K, T, call) { let lo = 0.01, hi = 5; for (let i = 0; i < 60; i++) { const mid = (lo + hi) / 2; if (P.price(F0, K, T, mid, call) > target) hi = mid; else lo = mid; } return (lo + hi) / 2; };
  // ---------- constants / clock ----------
  CG.NOW = new Date(2026, 8, 6, 14, 30, 0); // 06 Sep 2026 14:30 IST (mock clock)
  CG.ASSETS = {
    BTC: { symbol: 'BTC', name: 'Bitcoin', icon: '₿', price: 79521.0, chg24: -1.87, high: 82275.0, low: 78625.5, lot: 0.001, step: 500, iv: 0.424, futSymbol: 'BTCUSD' },
    ETH: { symbol: 'ETH', name: 'Ethereum', icon: 'Ξ', price: 2447.48, chg24: -2.06, high: 2546.15, low: 2430.6, lot: 0.01, step: 20, iv: 0.56, futSymbol: 'ETHUSD' },
    XAUT: { symbol: 'XAUT', name: 'Tether Gold', icon: 'Au', price: 4421.0, chg24: -1.55, high: 4491.78, low: 4374.24, lot: 0.001, step: 20, iv: 0.18, futSymbol: 'XAUTUSD' }
  };
  CG.EXPIRIES = ['07SEP26', '08SEP26', '09SEP26', '11SEP26', '18SEP26', '25SEP26', '30OCT26', '27NOV26', '25DEC26', '26MAR27'];
  // ---------- state ----------
  const st = (CG.state = { v2: true, density: 'comfortable', loggedIn: true, role: 'admin', currency: 'USD', conversionRate: 83.5, pnlBasis: 'mark', lotSizes: { BTC: 0.001, ETH: 0.01, XAUT: 0.001 }, asset: 'BTC', expiry: '25SEP26', exchangeConnected: false, tradingMode: 'paper', liveFeed: true, tourDone: false });
  try { const saved = JSON.parse(localStorage.getItem('cg-v2-state') || 'null'); if (saved) Object.assign(st, saved); } catch (e) { }
  CG.saveState = function () { try { localStorage.setItem('cg-v2-state', JSON.stringify(st)); } catch (e) { } };
  // ---------- events ----------
  const listeners = {};
  CG.on = (ev, fn) => { (listeners[ev] = listeners[ev] || []).push(fn); return () => { listeners[ev] = listeners[ev].filter((f) => f !== fn); }; };
  CG.emit = (ev, data) => { (listeners[ev] || []).forEach((f) => { try { f(data); } catch (e) { console.error(e); } }); };
  // ---------- options chain generator ----------
  const chainCache = {};
  CG.chain = function (asset, expiry) {
    const key = asset + ':' + expiry; if (chainCache[key]) return chainCache[key];
    const A = CG.ASSETS[asset]; const F0 = A.price; const T = Math.max(F.dte(expiry), 0.2) / 365; const r = rng(asset.length * 7919 + expiry.charCodeAt(0) * 31 + expiry.charCodeAt(1) * 17);
    const atm = Math.round(F0 / A.step) * A.step; const rows = [];
    for (let i = -20; i <= 20; i++) {
      const K = atm + i * A.step; const s = P.smile(K, F0, A.iv); const c = P.price(F0, K, T, s, true), p = P.price(F0, K, T, s, false); const gc = P.greeks(F0, K, T, s, true), gp = P.greeks(F0, K, T, s, false);
      const oiC = Math.round((800 + 5000 * Math.exp(-Math.pow(i - 1, 2) / 30) + r() * 1500) * (K % 1000 === 0 ? 1.6 : 1)); const oiP = Math.round((700 + 5200 * Math.exp(-Math.pow(i + 1, 2) / 30) + r() * 1500) * (K % 1000 === 0 ? 1.6 : 1));
      const mk = (mark, g, oi) => { const spread = Math.max(mark * 0.012, 2); const ivp = s * 100; return { mark: +mark.toFixed(1), bid: +Math.max(mark - spread / 2, 0.5).toFixed(1), ask: +(mark + spread / 2).toFixed(1), markIv: +ivp.toFixed(1), bidIv: +(ivp - 0.4).toFixed(1), askIv: +(ivp + 0.5).toFixed(1), oi, volume: Math.round(oi * (0.15 + r() * 0.5)), bidQty: Math.round(1000 + r() * 8000), askQty: Math.round(1000 + r() * 8000), delta: +g.delta.toFixed(4), gamma: +g.gamma.toFixed(6), theta: +g.theta.toFixed(2), vega: +g.vega.toFixed(2), chg24: +((r() - 0.55) * 30).toFixed(1), last: +(mark * (1 + (r() - 0.5) * 0.01)).toFixed(1), open: +(mark * (1 + (r() - 0.4) * 0.15)).toFixed(1), high: +(mark * (1.05 + r() * 0.1)).toFixed(1), low: +(mark * (0.85 + r() * 0.1)).toFixed(1) }; };
      rows.push({ strike: K, atm: i === 0, itmCall: K < F0, itmPut: K > F0, call: mk(c, gc, oiC), put: mk(p, gp, oiP), callSymbol: 'C-' + asset + '-' + K + '-' + expiry.slice(0, 2) + ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'].indexOf(expiry.slice(2, 5)) + 1 + expiry.slice(5), putSymbol: 'P-' + asset + '-' + K + '-' + expiry });
    }
    chainCache[key] = { asset, expiry, spot: F0, atm, rows, T };
    return chainCache[key];
  };
  CG.quote = function (asset, expiry, strike, type) { const ch = CG.chain(asset, expiry); const row = ch.rows.find((r) => r.strike === strike); if (!row) { const A = CG.ASSETS[asset]; const T = Math.max(F.dte(expiry), 0.2) / 365; const s = P.smile(strike, A.price, A.iv); const m = P.price(A.price, strike, T, s, type === 'CALL'); return { mark: +m.toFixed(1), bid: +(m * 0.994).toFixed(1), ask: +(m * 1.006).toFixed(1), markIv: +(s * 100).toFixed(1), delta: 0, gamma: 0, theta: 0, vega: 0, oi: 0 }; } return type === 'CALL' ? row.call : row.put; };
  // ---------- payoff / strategy analytics ----------
  // legs: [{type:'CALL'|'PUT'|'FUTURE', side:'BUY'|'SELL', strike, expiry, lots, price, iv?}] ; lots × lotSize (in asset units) = quantity
  CG.analyze = function (legs, asset, opts) {
    opts = opts || {}; const A = CG.ASSETS[asset || 'BTC']; const F0 = opts.spot || A.price; const lot = (st.lotSizes[asset] || A.lot); const n = opts.points || 161; const lo = opts.min || F0 * 0.8, hi = opts.max || F0 * 1.2;
    const daysTo = (l) => l.type === 'FUTURE' ? 0 : F.dte(l.expiry);
    const maxDte = Math.max(0, ...legs.map(daysTo)); const targetDays = opts.targetDays != null ? Math.min(opts.targetDays, maxDte) : 0;
    const pnlAt = (S, daysLeftOfMax) => legs.reduce((sum, l) => { const q = (l.lots || 1) * lot; const sign = l.side === 'BUY' ? 1 : -1; let val; if (l.type === 'FUTURE') val = S - (l.price || F0); else { const dte = Math.max(daysTo(l) - (maxDte - daysLeftOfMax), 0); const T = dte / 365; const s = (l.iv || (P.smile(l.strike, F0, A.iv) * 100)) / 100 * (1 + (opts.ivShift || 0)); val = P.price(S, l.strike, T, s, l.type === 'CALL') - (l.price || 0); } return sum + sign * val * q; }, 0);
    const pts = []; for (let i = 0; i < n; i++) { const S = lo + (hi - lo) * i / (n - 1); pts.push({ price: S, pnlExpiry: pnlAt(S, 0), pnlTarget: pnlAt(S, Math.max(maxDte - targetDays, 0)) }); }
    const exp = pts.map((p) => p.pnlExpiry); let maxProfit = Math.max(...exp), maxLoss = Math.min(...exp);
    const netDelta = legs.reduce((s, l) => s + (l.side === 'BUY' ? 1 : -1) * (l.type === 'FUTURE' ? 1 : l.type === 'CALL' ? 1 : -1) * (l.lots || 1), 0);
    const slopeR = exp[n - 1] - exp[n - 2], slopeL = exp[0] - exp[1];
    const unlimitedProfit = slopeR > 1e-9 || slopeL > 1e-9; const unlimitedLoss = slopeR < -1e-9 || slopeL < -1e-9;
    if (unlimitedProfit) maxProfit = Infinity; if (unlimitedLoss) maxLoss = -Infinity;
    const breakevens = []; for (let i = 1; i < n; i++) { if ((exp[i - 1] < 0 && exp[i] >= 0) || (exp[i - 1] > 0 && exp[i] <= 0)) { const a = pts[i - 1], b = pts[i]; breakevens.push(+(a.price + (0 - a.pnlExpiry) * (b.price - a.price) / (b.pnlExpiry - a.pnlExpiry)).toFixed(0)); } }
    const netPremium = legs.reduce((s, l) => l.type === 'FUTURE' ? s : s + (l.side === 'SELL' ? 1 : -1) * (l.price || 0) * (l.lots || 1) * lot, 0); // + credit, - debit
    const vT = A.iv * Math.sqrt(Math.max(maxDte, 0.5) / 365); const prob = (x) => N((Math.log(x / F0)) / vT);
    let pop = null; if (breakevens.length === 1) { pop = exp[n - 1] > 0 ? 1 - prob(breakevens[0]) : prob(breakevens[0]); } else if (breakevens.length >= 2) { const inside = prob(breakevens[1]) - prob(breakevens[0]); const midIdx = Math.round((n - 1) / 2); const midPos = pnlAt((breakevens[0] + breakevens[1]) / 2, 0) > 0; pop = midPos ? inside : 1 - inside; } else if (legs.length) pop = exp[Math.round(n / 2)] > 0 ? 0.99 : 0.01;
    const greeks = legs.reduce((g, l) => { if (l.type === 'FUTURE') { g.delta += (l.side === 'BUY' ? 1 : -1) * (l.lots || 1) * lot; return g; } const T = Math.max(daysTo(l), 0) / 365; const s = (l.iv || P.smile(l.strike, F0, A.iv) * 100) / 100; const gg = P.greeks(F0, l.strike, T, s, l.type === 'CALL'); const q = (l.lots || 1) * lot * (l.side === 'BUY' ? 1 : -1); g.delta += gg.delta * q; g.gamma += gg.gamma * q; g.theta += gg.theta * q; g.vega += gg.vega * q; return g; }, { delta: 0, gamma: 0, theta: 0, vega: 0 });
    const margin = legs.reduce((s, l) => { const q = (l.lots || 1) * lot; if (l.type === 'FUTURE') return s + F0 * q * 0.05; if (l.side === 'BUY') return s + (l.price || 0) * q; return s + Math.max(F0 * q * 0.08, (l.price || 0) * q * 1.5); }, 0);
    const sd = F0 * A.iv * Math.sqrt(Math.max(maxDte, 1) / 365);
    return { points: pts, maxProfit, maxLoss, breakevens, netPremium, pop: pop == null ? null : Math.max(0, Math.min(1, pop)), greeks, margin, spot: F0, lot, maxDte, sd, rewardRisk: isFinite(maxProfit) && isFinite(maxLoss) && maxLoss !== 0 ? Math.abs(maxProfit / maxLoss) : null, netDelta };
  };
  // ---------- strategy templates (28) ----------
  CG.TEMPLATES = [
    { name: 'Buy Call', category: 'Bullish', description: 'Buy a call. Unlimited upside, limited risk to premium paid.', legs: [{ type: 'CALL', side: 'BUY', k: 0 }] },
    { name: 'Sell Put', category: 'Bullish', description: 'Bullish strategy earning premium. Profit if price stays above strike.', legs: [{ type: 'PUT', side: 'SELL', k: 0 }] },
    { name: 'Bull Call Spread', category: 'Bullish', description: 'Buy ATM call, sell OTM call. Limited risk and reward.', legs: [{ type: 'CALL', side: 'BUY', k: 0 }, { type: 'CALL', side: 'SELL', k: 2 }] },
    { name: 'Bull Put Spread', category: 'Bullish', description: 'Sell ATM put, buy OTM put. Credit spread strategy.', legs: [{ type: 'PUT', side: 'SELL', k: 0 }, { type: 'PUT', side: 'BUY', k: -2 }] },
    { name: 'Long Synthetic Future', category: 'Bullish', description: 'Buy call and sell put at same strike. Mimics long futures position.', legs: [{ type: 'CALL', side: 'BUY', k: 0 }, { type: 'PUT', side: 'SELL', k: 0 }] },
    { name: 'Buy Put', category: 'Bearish', description: 'Buy a put. Profits from a fall, risk limited to premium paid.', legs: [{ type: 'PUT', side: 'BUY', k: 0 }] },
    { name: 'Sell Call', category: 'Bearish', description: 'Bearish strategy earning premium. Profit if price stays below strike.', legs: [{ type: 'CALL', side: 'SELL', k: 0 }] },
    { name: 'Bear Put Spread', category: 'Bearish', description: 'Buy ATM put, sell OTM put. Limited risk debit spread.', legs: [{ type: 'PUT', side: 'BUY', k: 0 }, { type: 'PUT', side: 'SELL', k: -2 }] },
    { name: 'Bear Call Spread', category: 'Bearish', description: 'Sell ATM call, buy OTM call. Credit spread strategy.', legs: [{ type: 'CALL', side: 'SELL', k: 0 }, { type: 'CALL', side: 'BUY', k: 2 }] },
    { name: 'Short Synthetic Future', category: 'Bearish', description: 'Sell call and buy put at same strike. Mimics short futures position.', legs: [{ type: 'CALL', side: 'SELL', k: 0 }, { type: 'PUT', side: 'BUY', k: 0 }] },
    { name: 'Long Straddle', category: 'Neutral', description: 'Buy call and put at same strike. Profit from big move in either direction.', legs: [{ type: 'CALL', side: 'BUY', k: 0 }, { type: 'PUT', side: 'BUY', k: 0 }] },
    { name: 'Short Straddle', category: 'Neutral', description: 'Sell call and put at same strike. Profit from low volatility.', legs: [{ type: 'CALL', side: 'SELL', k: 0 }, { type: 'PUT', side: 'SELL', k: 0 }] },
    { name: 'Long Strangle', category: 'Neutral', description: 'Buy OTM call and put. Cheaper than straddle, needs bigger move.', legs: [{ type: 'CALL', side: 'BUY', k: 2 }, { type: 'PUT', side: 'BUY', k: -2 }] },
    { name: 'Short Strangle', category: 'Neutral', description: 'Sell OTM call and put. Profit if price stays in range.', legs: [{ type: 'CALL', side: 'SELL', k: 2 }, { type: 'PUT', side: 'SELL', k: -2 }] },
    { name: 'Iron Condor', category: 'Neutral', description: 'Sell call spread and put spread. Profits from range-bound movement.', legs: [{ type: 'PUT', side: 'BUY', k: -4 }, { type: 'PUT', side: 'SELL', k: -2 }, { type: 'CALL', side: 'SELL', k: 2 }, { type: 'CALL', side: 'BUY', k: 4 }] },
    { name: 'Reverse Iron Condor', category: 'Neutral', description: 'Buy call spread and put spread. Profits from large moves in either direction.', legs: [{ type: 'PUT', side: 'SELL', k: -4 }, { type: 'PUT', side: 'BUY', k: -2 }, { type: 'CALL', side: 'BUY', k: 2 }, { type: 'CALL', side: 'SELL', k: 4 }] },
    { name: 'Iron Butterfly', category: 'Neutral', description: 'Sell ATM straddle, buy OTM strangle. Limited risk neutral strategy.', legs: [{ type: 'PUT', side: 'BUY', k: -3 }, { type: 'PUT', side: 'SELL', k: 0 }, { type: 'CALL', side: 'SELL', k: 0 }, { type: 'CALL', side: 'BUY', k: 3 }] },
    { name: 'Reverse Iron Butterfly', category: 'Neutral', description: 'Buy ATM straddle, sell OTM strangle. Profits from big moves.', legs: [{ type: 'PUT', side: 'SELL', k: -3 }, { type: 'PUT', side: 'BUY', k: 0 }, { type: 'CALL', side: 'BUY', k: 0 }, { type: 'CALL', side: 'SELL', k: 3 }] },
    { name: 'Long Call Butterfly', category: 'Neutral', description: 'Buy 1 ITM call, sell 2 ATM calls, buy 1 OTM call. Max profit at ATM.', legs: [{ type: 'CALL', side: 'BUY', k: -2 }, { type: 'CALL', side: 'SELL', k: 0, lots: 2 }, { type: 'CALL', side: 'BUY', k: 2 }] },
    { name: 'Long Put Butterfly', category: 'Neutral', description: 'Buy 1 ITM put, sell 2 ATM puts, buy 1 OTM put. Max profit at ATM.', legs: [{ type: 'PUT', side: 'BUY', k: 2 }, { type: 'PUT', side: 'SELL', k: 0, lots: 2 }, { type: 'PUT', side: 'BUY', k: -2 }] },
    { name: 'Long Call Condor', category: 'Neutral', description: 'Buy ITM call, sell 2 different ATM calls, buy OTM call. Wider profit zone than butterfly.', legs: [{ type: 'CALL', side: 'BUY', k: -3 }, { type: 'CALL', side: 'SELL', k: -1 }, { type: 'CALL', side: 'SELL', k: 1 }, { type: 'CALL', side: 'BUY', k: 3 }] },
    { name: 'Long Calendar with Calls', category: 'Neutral', description: 'Sell near-term call, buy longer-term call at same strike. Profits from time decay.', legs: [{ type: 'CALL', side: 'SELL', k: 0, expiryOffset: 0 }, { type: 'CALL', side: 'BUY', k: 0, expiryOffset: 1 }] },
    { name: 'Long Calendar with Puts', category: 'Neutral', description: 'Sell near-term put, buy longer-term put at same strike. Profits from time decay.', legs: [{ type: 'PUT', side: 'SELL', k: 0, expiryOffset: 0 }, { type: 'PUT', side: 'BUY', k: 0, expiryOffset: 1 }] },
    { name: 'Long Gut', category: 'Neutral', description: 'Buy ITM call and ITM put. High cost but profits from large moves.', legs: [{ type: 'CALL', side: 'BUY', k: -2 }, { type: 'PUT', side: 'BUY', k: 2 }] },
    { name: 'Strip', category: 'Neutral', description: 'Buy 1 ATM call and 2 ATM puts. Profits more from downside move.', legs: [{ type: 'CALL', side: 'BUY', k: 0 }, { type: 'PUT', side: 'BUY', k: 0, lots: 2 }] },
    { name: 'Strap', category: 'Neutral', description: 'Buy 2 ATM calls and 1 ATM put. Profits more from upside move.', legs: [{ type: 'CALL', side: 'BUY', k: 0, lots: 2 }, { type: 'PUT', side: 'BUY', k: 0 }] },
    { name: 'Jade Lizard', category: 'Others', description: 'Sell put spread + sell OTM call. No upside risk with premium collection.', legs: [{ type: 'PUT', side: 'BUY', k: -4 }, { type: 'PUT', side: 'SELL', k: -2 }, { type: 'CALL', side: 'SELL', k: 2 }] },
    { name: 'Reverse Jade Lizard', category: 'Others', description: 'Sell call spread + sell OTM put. No downside risk with premium collection.', legs: [{ type: 'CALL', side: 'BUY', k: 4 }, { type: 'CALL', side: 'SELL', k: 2 }, { type: 'PUT', side: 'SELL', k: -2 }] }
  ];
  // materialise a template into concrete legs at the current chain
  let legSeq = 100;
  CG.newLegId = () => 'leg_' + (legSeq++);
  CG.templateLegs = function (tpl, asset, expiry) {
    asset = asset || st.asset; expiry = expiry || st.expiry; const ch = CG.chain(asset, expiry); const A = CG.ASSETS[asset]; const ei = CG.EXPIRIES.indexOf(expiry);
    return tpl.legs.map((l) => { const exp = l.expiryOffset ? CG.EXPIRIES[Math.min(ei + l.expiryOffset, CG.EXPIRIES.length - 1)] : expiry; const strike = ch.atm + l.k * A.step; const q = CG.quote(asset, exp, strike, l.type); return { id: CG.newLegId(), type: l.type, side: l.side, strike, expiry: exp, lots: l.lots || 1, price: q.mark, iv: q.markIv, status: 'OPEN', isAdjustment: false, symbol: (l.type === 'CALL' ? 'C-' : 'P-') + asset + '-' + strike + '-' + exp }; });
  };
  // ---------- mock data ----------
  const M = (CG.mock = {});
  M.user = { id: 'u_1001', name: 'Demo Trader', email: 'demo@hapiecoin.com', mobile: '+91 98765 43210', role: 'admin', avatar: 'rocket', referralCode: 'REF_DEMO4K2', commissionPct: 20, joinedAt: '2026-03-12', promoEmails: true };
  M.plans = [
    { id: 'p_free', name: 'Free Plan', description: 'Get started with paper trading and the live options chain.', isActive: true, features: ['Live options chain with Greeks & IV', 'Payoff diagrams', '5 paper trades / month', 'Community support'], monthly: { price: 0, discountPrice: 0, featureLimits: { paper_trading: 5, live_trading: 0 } }, quarterly: { price: 0, discountPrice: 0, featureLimits: { paper_trading: 5, live_trading: 0 } }, yearly: { price: 0, discountPrice: 0, featureLimits: { paper_trading: 5, live_trading: 0 } }, menuItems: ['Options Chain', 'Payoff Diagram'] },
    { id: 'p_basic', name: 'Basic Plan', description: 'For active paper traders who want the full toolkit.', isActive: true, features: ['Everything in Free', '50 paper trades / month', 'Strategy templates (28)', 'Greeks & P&L table', 'Email support'], monthly: { price: 499, discountPrice: 399, featureLimits: { paper_trading: 50, live_trading: 0 } }, quarterly: { price: 1299, discountPrice: 999, featureLimits: { paper_trading: 50, live_trading: 0 } }, yearly: { price: 4499, discountPrice: 3599, featureLimits: { paper_trading: 50, live_trading: 0 } }, menuItems: ['Options Chain', 'Payoff Diagram', 'Strategy Templates', 'Greeks'] },
    { id: 'p_pro', name: 'Pro Plan', description: 'Unlimited paper trading and live trading on Delta Exchange.', isActive: true, features: ['Everything in Basic', 'Unlimited paper trades', '25 live trades / month', 'Market Analytics', 'Priority support'], monthly: { price: 999, discountPrice: 799, featureLimits: { paper_trading: 0, live_trading: 25 } }, quarterly: { price: 2699, discountPrice: 2199, featureLimits: { paper_trading: 0, live_trading: 25 } }, yearly: { price: 8999, discountPrice: 7499, featureLimits: { paper_trading: 0, live_trading: 25 } }, menuItems: ['Options Chain', 'Payoff Diagram', 'Strategy Templates', 'Greeks', 'Live Trading', 'Market Analytics'] },
    { id: 'p_elite', name: 'Elite Plan', description: 'Everything unlimited, for professional desks.', isActive: true, features: ['Everything in Pro', 'Unlimited live trades', 'Reports export', 'Dedicated support (WhatsApp)'], monthly: { price: 1999, discountPrice: 1699, featureLimits: { paper_trading: 0, live_trading: 0 } }, quarterly: { price: 5399, discountPrice: 4499, featureLimits: { paper_trading: 0, live_trading: 0 } }, yearly: { price: 17999, discountPrice: 14999, featureLimits: { paper_trading: 0, live_trading: 0 } }, menuItems: ['Options Chain', 'Payoff Diagram', 'Strategy Templates', 'Greeks', 'Live Trading', 'Market Analytics', 'Reports Export'] }
  ];
  M.menuItems = [
    { id: 'm1', displayName: 'Options Chain', category: 'Trading', price: 0, isActive: true }, { id: 'm2', displayName: 'Payoff Diagram', category: 'Analytics', price: 0, isActive: true }, { id: 'm3', displayName: 'Strategy Templates', category: 'Trading', price: 199, isActive: true }, { id: 'm4', displayName: 'Greeks', category: 'Analytics', price: 149, isActive: true }, { id: 'm5', displayName: 'Live Trading', category: 'Trading', price: 499, isActive: true }, { id: 'm6', displayName: 'Market Analytics', category: 'Data', price: 299, isActive: true }, { id: 'm7', displayName: 'Reports Export', category: 'Data', price: 199, isActive: false }
  ];
  M.subscription = { planId: 'p_pro', planName: 'Pro Plan', interval: 'yearly', status: 'active', startedAt: '2026-01-01', expiresAt: '2026-12-31', price: 8999, paid: 7499, currency: 'INR', featureLimits: { paper_trading: 0, live_trading: 25 }, usage: { paper_trading: 14, live_trading: 3 } };
  M.payments = [
    { id: 'pay_9001', date: '2026-01-01T10:12:00', plan: 'Pro Plan', interval: 'Yearly', amount: 8848, coupon: 'WELCOME10', discount: 750, tax: 1349, status: 'success', method: 'Razorpay · UPI', invoice: 'INV-2026-0001' },
    { id: 'pay_8120', date: '2025-10-01T09:40:00', plan: 'Basic Plan', interval: 'Quarterly', amount: 1179, coupon: null, discount: 0, tax: 180, status: 'success', method: 'Razorpay · Card', invoice: 'INV-2025-0412' },
    { id: 'pay_8004', date: '2025-09-28T21:03:00', plan: 'Basic Plan', interval: 'Quarterly', amount: 1179, coupon: null, discount: 0, tax: 180, status: 'failed', method: 'Razorpay · Netbanking', invoice: null },
    { id: 'pay_7710', date: '2025-07-01T08:15:00', plan: 'Basic Plan', interval: 'Quarterly', amount: 1179, coupon: 'BASIC20', discount: 260, tax: 180, status: 'success', method: 'Razorpay · UPI', invoice: 'INV-2025-0201' }
  ];
  M.coupons = [
    { id: 'c1', code: 'BASIC20', description: 'Get 20% off your first plan', discountType: 'percent', discountValue: 20, minOrderAmount: 0, maxUses: 100, usedCount: 37, perUserLimit: 1, startsAt: '2026-01-01', expiresAt: '2026-12-31', scope: 'public_all_listed', plans: ['p_basic', 'p_pro'], intervals: ['monthly', 'quarterly', 'yearly'], isActive: true, assignedUsers: [] },
    { id: 'c2', code: 'WELCOME10', description: 'Welcome offer · 10% off any plan', discountType: 'percent', discountValue: 10, minOrderAmount: 499, maxUses: 1000, usedCount: 412, perUserLimit: 1, startsAt: '2025-06-01', expiresAt: '2026-12-31', scope: 'public_all_listed', plans: ['p_basic', 'p_pro', 'p_elite'], intervals: ['monthly', 'quarterly', 'yearly'], isActive: true, assignedUsers: [] },
    { id: 'c3', code: 'PRO500', description: '₹500 off Pro yearly', discountType: 'fixed', discountValue: 500, minOrderAmount: 5000, maxUses: 200, usedCount: 58, perUserLimit: 1, startsAt: '2026-06-01', expiresAt: '2026-10-31', scope: 'public_all_listed', plans: ['p_pro'], intervals: ['yearly'], isActive: true, assignedUsers: [] },
    { id: 'c4', code: 'COMMUNITY25', description: 'Community members & their referrals', discountType: 'percent', discountValue: 25, minOrderAmount: 0, maxUses: 500, usedCount: 121, perUserLimit: 2, startsAt: '2026-03-01', expiresAt: '2027-03-01', scope: 'private_community_listed', plans: ['p_basic', 'p_pro', 'p_elite'], intervals: ['quarterly', 'yearly'], isActive: true, assignedUsers: ['u_1001', 'u_1007', 'u_1012'] },
    { id: 'c5', code: 'DIWALI30', description: 'Festive offer (expired)', discountType: 'percent', discountValue: 30, minOrderAmount: 0, maxUses: 300, usedCount: 300, perUserLimit: 1, startsAt: '2025-10-15', expiresAt: '2025-11-15', scope: 'public_all_listed', plans: ['p_basic', 'p_pro'], intervals: ['monthly', 'quarterly', 'yearly'], isActive: false, assignedUsers: [] }
  ];
  const firstNames = ['Arjun', 'Priya', 'Rohit', 'Sneha', 'Raj', 'Kavita', 'Vikram', 'Ananya', 'Karthik', 'Divya', 'Manish', 'Pooja', 'Suresh', 'Neha', 'Aditya', 'Meera', 'Rahul', 'Shreya', 'Nikhil', 'Isha', 'Varun', 'Riya', 'Deepak', 'Tanvi', 'Sanjay', 'Aarti', 'Harsh', 'Nisha', 'Gaurav', 'Swati', 'Amit', 'Lakshmi', 'Pranav', 'Ritika', 'Yash', 'Simran', 'Mohit', 'Bhavya', 'Kunal', 'Anjali', 'Siddharth', 'Payal'];
  const lastNames = ['Mehta', 'Sharma', 'Kumar', 'Reddy', 'Patel', 'Desai', 'Singh', 'Iyer', 'Nair', 'Gupta', 'Joshi', 'Menon', 'Rao', 'Bose', 'Kapoor', 'Chawla', 'Verma', 'Pillai', 'Shah', 'Mishra'];
  const ur = rng(4242);
  M.users = firstNames.map((fn, i) => { const ln = lastNames[i % lastNames.length]; const planIdx = [0, 1, 2, 0, 2, 1, 3, 0, 2, 1][i % 10]; const plan = M.plans[planIdx]; const joined = new Date(2025, 5 + Math.floor(ur() * 15), 1 + Math.floor(ur() * 27)); const subscribed = planIdx ? new Date(joined.getTime() + 86400000 * Math.floor(ur() * 20)) : null; const interval = ['monthly', 'quarterly', 'yearly'][i % 3]; const ends = subscribed ? new Date(subscribed.getTime() + 86400000 * (interval === 'monthly' ? 30 : interval === 'quarterly' ? 90 : 365)) : null; const status = !planIdx ? 'free' : ends < CG.NOW ? 'expired' : i % 11 === 5 ? 'cancelled' : 'active'; return { id: 'u_' + (1001 + i), name: fn + ' ' + ln, email: (fn + '.' + ln).toLowerCase() + '@example.com', mobile: '+91 9' + String(100000000 + Math.floor(ur() * 899999999)), role: i === 0 ? 'admin' : 'user', planId: plan.id, plan: plan.name, interval, status, joinedAt: joined.toISOString().slice(0, 10), subscribedAt: subscribed ? subscribed.toISOString().slice(0, 10) : null, endsAt: ends ? ends.toISOString().slice(0, 10) : null, lastLoginAt: new Date(CG.NOW - 86400000 * Math.floor(ur() * (i % 7 === 3 ? 60 : 6))).toISOString().slice(0, 10), activated: i % 9 !== 8, referralCode: 'REF_' + fn.slice(0, 3).toUpperCase() + String(1000 + i), commissionPct: [10, 15, 20, 25][i % 4], referrals: Math.floor(ur() * 8), featureLimits: { paper_trading: 0, live_trading: 0 }, lotSizes: { BTC: 0.001, ETH: 0.01, XAUT: 0.001 }, amountPaid: planIdx ? [0, 499, 999, 1999][planIdx] * (interval === 'monthly' ? 1 : interval === 'quarterly' ? 2.7 : 9) : 0 }; });
  M.users[0] = Object.assign(M.users[0], { name: M.user.name, email: M.user.email, planId: 'p_pro', plan: 'Pro Plan', interval: 'yearly', status: 'active', subscribedAt: '2026-01-01', endsAt: '2026-12-31', referralCode: M.user.referralCode, commissionPct: 20, referrals: 6, amountPaid: 7499 });
  M.referrals = { code: M.user.referralCode, link: 'https://hapiecoin.com/auth?tab=signup&ref=' + M.user.referralCode, commissionPct: 20, totalReferrals: 6, totalEarned: 3299, paid: 2100, pending: 1199, users: [
    { id: 'u_1007', name: 'Ananya Iyer', email: 'ananya.iyer@example.com', joinedAt: '2026-02-14', plan: 'Pro Plan', interval: 'yearly', amount: 7499, commission: 1499.8, status: 'paid', paidAt: '2026-03-05' },
    { id: 'u_1012', name: 'Pooja Menon', email: 'pooja.menon@example.com', joinedAt: '2026-03-02', plan: 'Basic Plan', interval: 'quarterly', amount: 999, commission: 199.8, status: 'paid', paidAt: '2026-04-02' },
    { id: 'u_1019', name: 'Nikhil Rao', email: 'nikhil.rao@example.com', joinedAt: '2026-04-21', plan: 'Basic Plan', interval: 'monthly', amount: 399, commission: 79.8, status: 'paid', paidAt: '2026-05-06' },
    { id: 'u_1023', name: 'Deepak Chawla', email: 'deepak.chawla@example.com', joinedAt: '2026-06-09', plan: 'Pro Plan', interval: 'quarterly', amount: 2199, commission: 439.8, status: 'pending', paidAt: null },
    { id: 'u_1031', name: 'Amit Verma', email: 'amit.verma@example.com', joinedAt: '2026-07-30', plan: 'Elite Plan', interval: 'monthly', amount: 1699, commission: 339.8, status: 'pending', paidAt: null },
    { id: 'u_1038', name: 'Bhavya Shah', email: 'bhavya.shah@example.com', joinedAt: '2026-08-28', plan: null, interval: null, amount: 0, commission: 0, status: 'not_paid', paidAt: null }
  ] };
  M.commissions = M.users.filter((u) => u.referrals > 0).slice(0, 14).map((u, i) => { const total = Math.round(u.referrals * (600 + ur() * 1400)); const paid = i % 3 === 0 ? total : Math.round(total * ur() * 0.6); return { referrerId: u.id, referrer: u.name, email: u.email, referrals: u.referrals, commissionPct: u.commissionPct, total, paid, pending: total - paid, month: '2026-' + String(3 + (i % 6)).padStart(2, '0'), status: paid >= total ? 'paid' : 'pending' }; });
  M.banners = [
    { id: 'b1', title: 'Welcome Offer', description: 'Get 20% off your first plan with code BASIC20', linkUrl: 'https://hapiecoin.com/subscription', startsAt: '2026-09-01T00:00', endsAt: '2026-10-31T23:59', frequency: 'once_per_day', type: 'popup', isActive: true, image: 'gradient:215 50% 55%/225 45% 45%', createdAt: '2026-08-30' },
    { id: 'b2', title: 'Live Trading is here', description: 'Connect your Delta Exchange API key and trade real orders from the builder.', linkUrl: 'https://hapiecoin.com/analyse', startsAt: '2026-08-15T00:00', endsAt: '2026-12-31T23:59', frequency: 'once_per_session', type: 'popup', isActive: true, image: 'gradient:142 71% 35%/168 100% 34%', createdAt: '2026-08-14' },
    { id: 'b3', title: 'Diwali Sale', description: '30% off yearly plans · ended', linkUrl: 'https://hapiecoin.com/subscription', startsAt: '2025-10-15T00:00', endsAt: '2025-11-15T23:59', frequency: 'every_time', type: 'popup', isActive: false, image: 'gradient:38 92% 50%/0 72% 51%', createdAt: '2025-10-10' }
  ];
  M.campaigns = [
    { id: 'cmp_1', subject: 'Your weekly options report is ready', message: 'Hi {{name}}, your strategies made {{pnl}} this week. Log in to review your positions.', sentAt: '2026-09-01T09:00:00', sentBy: 'Demo Trader', recipients: 38, delivered: 36, failed: 2, segment: 'All users' },
    { id: 'cmp_2', subject: 'Live trading now available on Pro', message: 'Hi {{name}}, connect Delta Exchange in Settings → API Settings to place real orders.', sentAt: '2026-08-15T18:30:00', sentBy: 'Demo Trader', recipients: 21, delivered: 21, failed: 0, segment: 'Paid users' }
  ];
  M.brokers = [{ id: 'br_1', name: 'Delta Exchange India', feePercentage: 0.05, gstPercentage: 18, feeCapPercentage: 10, scope: 'GLOBAL', isDefault: true }, { id: 'br_2', name: 'Delta Exchange Global', feePercentage: 0.03, gstPercentage: 0, feeCapPercentage: 10, scope: 'USER', isDefault: false }];
  M.wallet = { available: 1000.0, marginUsed: 312.4, equity: 1330.28, currency: 'USD' };
  // strategies
  const mkLegs = (asset, expiry, defs) => defs.map((d) => { const q = CG.quote(asset, expiry, d.strike, d.type); const entry = d.entry != null ? d.entry : +(q.mark * (d.f || 1)).toFixed(1); return { id: CG.newLegId(), type: d.type, side: d.side, strike: d.strike, expiry, lots: d.lots || 1, price: entry, entryPremium: entry, currentPrice: q.mark, exitPremium: d.exit != null ? d.exit : null, iv: q.markIv, status: d.status || 'OPEN', isAdjustment: !!d.adj, symbol: (d.type === 'CALL' ? 'C-' : d.type === 'PUT' ? 'P-' : 'F-') + asset + '-' + (d.strike || '') + '-' + expiry, unit: 'LOTS' }; });
  const pnlHist = (n, seed, end) => { const r = rng(seed); const out = []; let v = 0; for (let i = n - 1; i >= 0; i--) { v += (r() - 0.45) * 6; out.push({ date: new Date(CG.NOW - i * 86400000).toISOString().slice(0, 10), pnl: +v.toFixed(2) }); } if (end != null) { const k = end / (out[out.length - 1].pnl || 1); out.forEach((o) => (o.pnl = +(o.pnl * k).toFixed(2))); } return out; };
  M.strategies = [
    { id: 's_301', name: 'BTC Bull Call Spread · Sep', asset: 'BTC', status: 'PAPER', tradingMode: 'PAPER', templateName: 'Bull Call Spread', createdAt: '2026-08-28T10:20:00', startedAt: '2026-08-28T10:25:00', daysTracked: 9, brokerId: 'br_1', legs: mkLegs('BTC', '25SEP26', [{ type: 'CALL', side: 'BUY', strike: 80000, lots: 10, f: 1.08 }, { type: 'CALL', side: 'SELL', strike: 84000, lots: 10, f: 1.12 }]), realizedPnl: 0, unrealizedPnl: 11.16, pnlHistory: pnlHist(10, 11, 11.16) },
    { id: 's_302', name: 'ETH Iron Condor weekly', asset: 'ETH', status: 'PAPER', tradingMode: 'PAPER', templateName: 'Iron Condor', createdAt: '2026-09-02T14:00:00', startedAt: '2026-09-02T14:05:00', daysTracked: 4, brokerId: 'br_1', legs: mkLegs('ETH', '11SEP26', [{ type: 'PUT', side: 'BUY', strike: 2300, lots: 5 }, { type: 'PUT', side: 'SELL', strike: 2360, lots: 5, f: 0.95 }, { type: 'CALL', side: 'SELL', strike: 2540, lots: 5, f: 0.94 }, { type: 'CALL', side: 'BUY', strike: 2600, lots: 5 }]), realizedPnl: 0, unrealizedPnl: 3.42, pnlHistory: pnlHist(5, 12, 3.42) },
    { id: 's_303', name: 'BTC TEST', asset: 'BTC', status: 'PAPER', tradingMode: 'PAPER', templateName: 'Custom Strategy', createdAt: '2026-08-20T09:00:00', startedAt: '2026-08-20T09:10:00', daysTracked: 17, brokerId: 'br_1', legs: mkLegs('BTC', '25SEP26', [{ type: 'PUT', side: 'SELL', strike: 78000, lots: 1, entry: 2975.9, status: 'OPEN' }, { type: 'CALL', side: 'SELL', strike: 86000, lots: 1, entry: 1255.9, exit: 980.0, status: 'SQUARED_OFF' }, { type: 'CALL', side: 'BUY', strike: 82000, lots: 1, entry: 2107.6, adj: true }]), realizedPnl: 0.28, unrealizedPnl: 0.72, pnlHistory: pnlHist(18, 13, 1.0) },
    { id: 's_304', name: 'BTC Short Strangle · Oct', asset: 'BTC', status: 'LIVE', tradingMode: 'LIVE', templateName: 'Short Strangle', createdAt: '2026-09-04T11:30:00', startedAt: '2026-09-04T11:32:00', daysTracked: 2, brokerId: 'br_1', orderBatchId: 'batch_77', legs: mkLegs('BTC', '30OCT26', [{ type: 'CALL', side: 'SELL', strike: 90000, lots: 2, f: 1.03 }, { type: 'PUT', side: 'SELL', strike: 70000, lots: 2, f: 1.02 }]), realizedPnl: 0, unrealizedPnl: 4.86, pnlHistory: pnlHist(3, 14, 4.86), orders: [{ legIdx: 0, status: 'filled', orderId: 'DX-88121', fill: null }, { legIdx: 1, status: 'filled', orderId: 'DX-88122', fill: null }] },
    { id: 's_305', name: 'ETH Long Straddle · earnings', asset: 'ETH', status: 'DRAFT', tradingMode: null, templateName: 'Long Straddle', createdAt: '2026-09-05T16:45:00', startedAt: null, daysTracked: 0, brokerId: null, legs: mkLegs('ETH', '25SEP26', [{ type: 'CALL', side: 'BUY', strike: 2440, lots: 3 }, { type: 'PUT', side: 'BUY', strike: 2440, lots: 3 }]), realizedPnl: 0, unrealizedPnl: 0, pnlHistory: [] },
    { id: 's_306', name: 'XAUT Bull Put Spread', asset: 'XAUT', status: 'DRAFT', tradingMode: null, templateName: 'Bull Put Spread', createdAt: '2026-09-03T12:10:00', startedAt: null, daysTracked: 0, brokerId: null, legs: mkLegs('XAUT', '25SEP26', [{ type: 'PUT', side: 'SELL', strike: 4420, lots: 5 }, { type: 'PUT', side: 'BUY', strike: 4380, lots: 5 }]), realizedPnl: 0, unrealizedPnl: 0, pnlHistory: [] },
    { id: 's_307', name: 'BTC Jade Lizard', asset: 'BTC', status: 'DRAFT', tradingMode: null, templateName: 'Jade Lizard', createdAt: '2026-08-31T08:00:00', startedAt: null, daysTracked: 0, brokerId: null, legs: mkLegs('BTC', '25SEP26', [{ type: 'PUT', side: 'BUY', strike: 76000, lots: 2 }, { type: 'PUT', side: 'SELL', strike: 78000, lots: 2 }, { type: 'CALL', side: 'SELL', strike: 84000, lots: 2 }]), realizedPnl: 0, unrealizedPnl: 0, pnlHistory: [] },
    { id: 's_308', name: 'BTC Iron Butterfly · Aug', asset: 'BTC', status: 'ARCHIVED', tradingMode: 'PAPER', templateName: 'Iron Butterfly', createdAt: '2026-07-30T10:00:00', startedAt: '2026-07-30T10:05:00', closedAt: '2026-08-28T12:00:00', daysTracked: 29, brokerId: 'br_1', legs: mkLegs('BTC', '25SEP26', [{ type: 'PUT', side: 'BUY', strike: 74000, lots: 4, entry: 1100, exit: 620, status: 'SQUARED_OFF' }, { type: 'PUT', side: 'SELL', strike: 79000, lots: 4, entry: 2900, exit: 2210, status: 'SQUARED_OFF' }, { type: 'CALL', side: 'SELL', strike: 79000, lots: 4, entry: 3200, exit: 2650, status: 'SQUARED_OFF' }, { type: 'CALL', side: 'BUY', strike: 84000, lots: 4, entry: 1300, exit: 900, status: 'SQUARED_OFF' }]), realizedPnl: 3.32, unrealizedPnl: 0, pnlHistory: pnlHist(29, 15, 3.32) },
    { id: 's_309', name: 'ETH Short Straddle · Jul', asset: 'ETH', status: 'ARCHIVED', tradingMode: 'LIVE', templateName: 'Short Straddle', createdAt: '2026-07-10T10:00:00', startedAt: '2026-07-10T10:02:00', closedAt: '2026-07-24T15:30:00', daysTracked: 14, brokerId: 'br_1', legs: mkLegs('ETH', '25SEP26', [{ type: 'CALL', side: 'SELL', strike: 2440, lots: 4, entry: 210, exit: 262, status: 'SQUARED_OFF' }, { type: 'PUT', side: 'SELL', strike: 2440, lots: 4, entry: 205, exit: 120, status: 'SQUARED_OFF' }]), realizedPnl: -1.32, unrealizedPnl: 0, pnlHistory: pnlHist(14, 16, -1.32) }
  ];
  M.strategies.forEach((s) => { s.legsCount = s.legs.length; s.totalPnl = +(s.realizedPnl + s.unrealizedPnl).toFixed(2); });
  // market analytics data
  const coinDefs = [['BTC', 'Bitcoin', 79521, 1570e9], ['ETH', 'Ethereum', 2447.48, 295e9], ['SOL', 'Solana', 148.2, 70e9], ['BNB', 'BNB', 612.4, 89e9], ['XRP', 'XRP', 0.583, 33e9], ['DOGE', 'Dogecoin', 0.1312, 19e9], ['ADA', 'Cardano', 0.412, 14.6e9], ['AVAX', 'Avalanche', 27.9, 11e9], ['TRX', 'TRON', 0.162, 14e9], ['LINK', 'Chainlink', 13.4, 8e9], ['DOT', 'Polkadot', 5.92, 8.4e9], ['MATIC', 'Polygon', 0.62, 6e9], ['TON', 'Toncoin', 5.4, 13e9], ['SHIB', 'Shiba Inu', 0.0000178, 10.5e9], ['LTC', 'Litecoin', 74.1, 5.5e9], ['BCH', 'Bitcoin Cash', 352, 6.9e9], ['UNI', 'Uniswap', 7.8, 4.7e9], ['ATOM', 'Cosmos', 6.1, 2.4e9], ['NEAR', 'NEAR', 4.9, 5.3e9], ['APT', 'Aptos', 7.2, 3.3e9], ['ARB', 'Arbitrum', 0.71, 2.6e9], ['OP', 'Optimism', 1.62, 1.8e9], ['SUI', 'Sui', 0.98, 2.6e9], ['PEPE', 'Pepe', 0.0000091, 3.8e9], ['WIF', 'dogwifhat', 1.84, 1.8e9], ['AAVE', 'Aave', 128, 1.9e9], ['MKR', 'Maker', 2110, 1.9e9], ['LDO', 'Lido DAO', 1.22, 1.1e9], ['INJ', 'Injective', 19.8, 1.9e9], ['TIA', 'Celestia', 5.6, 1.1e9], ['SEI', 'Sei', 0.34, 1.0e9], ['FIL', 'Filecoin', 4.1, 2.3e9], ['STRK', 'Starknet', 0.52, 0.7e9], ['IMX', 'Immutable', 1.31, 2.0e9], ['GMX', 'GMX', 27.5, 0.27e9], ['CRV', 'Curve', 0.29, 0.35e9], ['SNX', 'Synthetix', 1.7, 0.55e9], ['BONK', 'Bonk', 0.0000201, 1.4e9], ['FLOKI', 'Floki', 0.000151, 1.45e9], ['ORDI', 'ORDI', 34.2, 0.72e9]];
  const cr = rng(777);
  M.coins = coinDefs.map(([sym, name, price, mcap], i) => { const chg = +((cr() - 0.55) * 8).toFixed(2); const oi = mcap * (0.02 + cr() * 0.08); const vol = mcap * (0.05 + cr() * 0.4); const liq = oi * (0.002 + cr() * 0.01); return { symbol: sym, name, price, chg24: chg, chg1h: +((cr() - 0.5) * 1.5).toFixed(2), chg4h: +((cr() - 0.5) * 3).toFixed(2), chg7d: +((cr() - 0.5) * 18).toFixed(2), marketCap: mcap, volume24h: vol, openInterest: oi, oiChg1h: +((cr() - 0.5) * 3).toFixed(2), oiChg24h: +((cr() - 0.45) * 9).toFixed(2), funding: +((cr() - 0.4) * 0.03).toFixed(4), lsRatio: +(0.8 + cr() * 0.7).toFixed(2), liq24h: liq, longLiq24h: liq * (0.4 + cr() * 0.3), shortLiq24h: 0, rsi: { '15m': Math.round(30 + cr() * 45), '1h': Math.round(30 + cr() * 45), '4h': Math.round(30 + cr() * 45), '12h': Math.round(30 + cr() * 45), '24h': Math.round(30 + cr() * 45), '1w': Math.round(30 + cr() * 45) }, rank: i + 1, sector: ['BTC', 'ETH', 'SOL', 'BNB', 'AVAX', 'ADA', 'DOT', 'ATOM', 'NEAR', 'APT', 'SUI', 'TON', 'TRX'].includes(sym) ? 'layer-1' : ['MATIC', 'ARB', 'OP', 'STRK', 'IMX'].includes(sym) ? 'layer-2' : ['UNI', 'AAVE', 'MKR', 'SNX', 'CRV', 'LDO', 'GMX'].includes(sym) ? 'defi' : ['DOGE', 'SHIB', 'PEPE', 'WIF', 'BONK', 'FLOKI'].includes(sym) ? 'memes' : 'other' }; });
  (function normaliseOi() { const target = 62.4e9 * 0.96; const sum = M.coins.reduce((s, c) => s + c.openInterest, 0); const k = target / sum; M.coins.forEach((c) => { c.openInterest *= k; c.liq24h *= k; c.longLiq24h *= k; }); })();
  M.coins.forEach((c) => (c.shortLiq24h = c.liq24h - c.longLiq24h));
  M.exchanges = [['Binance', 0.36], ['OKX', 0.14], ['Bybit', 0.18], ['Bitget', 0.08], ['Gate', 0.05], ['HTX', 0.04], ['CoinEx', 0.02], ['Hyperliquid', 0.07], ['Deribit', 0.04], ['Kraken', 0.02]].map(([name, share], i) => { const totalOi = 62.4e9; return { name, oiShare: share, openInterest: totalOi * share, volume24h: 180e9 * share * (0.8 + cr() * 0.4), funding: +((cr() - 0.4) * 0.02).toFixed(4), btcBalance: Math.round(80000 + cr() * 500000 * share * 3), btcBalanceChg24: +((cr() - 0.5) * 2).toFixed(2), btcBalanceChg7d: +((cr() - 0.5) * 5).toFixed(2), btcBalanceChg30d: +((cr() - 0.55) * 9).toFixed(2), liq24h: 210e6 * share * (0.7 + cr() * 0.6) }; });
  M.etfs = [['IBIT', 'iShares Bitcoin Trust', 'BlackRock', 62e9, 730000], ['FBTC', 'Fidelity Wise Origin Bitcoin', 'Fidelity', 22e9, 262000], ['GBTC', 'Grayscale Bitcoin Trust', 'Grayscale', 17e9, 205000], ['ARKB', 'ARK 21Shares Bitcoin', 'ARK/21Shares', 4.1e9, 49000], ['BITB', 'Bitwise Bitcoin', 'Bitwise', 3.9e9, 46500], ['HODL', 'VanEck Bitcoin', 'VanEck', 1.5e9, 18000], ['BTCO', 'Invesco Galaxy Bitcoin', 'Invesco', 0.6e9, 7200], ['BRRR', 'Valkyrie Bitcoin', 'CoinShares', 0.55e9, 6600], ['EZBC', 'Franklin Bitcoin', 'Franklin', 0.5e9, 6000], ['BTC', 'Grayscale Bitcoin Mini', 'Grayscale', 4.5e9, 54000]].map(([t, fund, issuer, aum, btc], i) => ({ ticker: t, fund, issuer, type: 'Spot', aum, btcHeld: btc, flow1d: +((cr() - 0.42) * 260e6).toFixed(0), chg24: +((cr() - 0.5) * 4).toFixed(2), volume24h: aum * (0.01 + cr() * 0.04), hold24: +((cr() - 0.45) * 1200).toFixed(0), premium: +((cr() - 0.5) * 0.4).toFixed(2), chg30: +((cr() - 0.4) * 12).toFixed(2), asset: 'bitcoin' }));
  M.ethEtfs = [['ETHA', 'iShares Ethereum Trust', 'BlackRock', 4.2e9], ['FETH', 'Fidelity Ethereum Fund', 'Fidelity', 1.4e9], ['ETHE', 'Grayscale Ethereum Trust', 'Grayscale', 4.6e9], ['ETH', 'Grayscale Ethereum Mini', 'Grayscale', 1.1e9], ['ETHW', 'Bitwise Ethereum', 'Bitwise', 0.35e9], ['ETHV', 'VanEck Ethereum', 'VanEck', 0.12e9]].map(([t, fund, issuer, aum]) => ({ ticker: t, fund, issuer, type: 'Spot', aum, ethHeld: Math.round(aum / 2447), flow1d: +((cr() - 0.45) * 60e6).toFixed(0), chg24: +((cr() - 0.5) * 4).toFixed(2), volume24h: aum * (0.02 + cr() * 0.05), premium: +((cr() - 0.5) * 0.5).toFixed(2), chg30: +((cr() - 0.4) * 10).toFixed(2), asset: 'ethereum' }));
  M.etfFlows = (function () { const out = []; let cum = 18.2e9; for (let i = 60; i >= 0; i--) { const flow = (cr() - 0.42) * 420e6; cum += flow; out.push({ date: new Date(CG.NOW - i * 86400000).toISOString().slice(0, 10), flow: Math.round(flow), cumulative: Math.round(cum), price: 79521 * (1 + (cr() - 0.5) * 0.12) }); } return out; })();
  M.fearGreed = (function () { const out = []; let v = 52; for (let i = 90; i >= 0; i--) { v = Math.max(8, Math.min(92, v + (cr() - 0.5) * 9)); out.push({ date: new Date(CG.NOW - i * 86400000).toISOString().slice(0, 10), value: Math.round(v) }); } return out; })();
  M.fearGreedNow = M.fearGreed[M.fearGreed.length - 1].value;
  M.fgLabel = (v) => (v < 25 ? 'Extreme Fear' : v < 45 ? 'Fear' : v < 55 ? 'Neutral' : v < 75 ? 'Greed' : 'Extreme Greed');
  M.liqHistory = (function () { const out = []; for (let i = 48; i >= 0; i--) { out.push({ time: new Date(CG.NOW - i * 3600000).toISOString(), long: Math.round(2e6 + cr() * 14e6), short: Math.round(1.5e6 + cr() * 12e6) }); } return out; })();
  M.liqFeed = (function () { const syms = ['BTC', 'ETH', 'SOL', 'DOGE', 'XRP', 'BNB', 'AVAX', 'PEPE', 'WIF', 'LINK']; const out = []; for (let i = 0; i < 30; i++) { const s = syms[Math.floor(cr() * syms.length)]; const coin = M.coins.find((c) => c.symbol === s); out.push({ time: new Date(CG.NOW - i * 12000 * (1 + cr() * 5)).toISOString(), exchange: ['Binance', 'OKX', 'Bybit'][Math.floor(cr() * 3)], symbol: s, side: cr() > 0.5 ? 'long' : 'short', price: coin.price * (1 + (cr() - 0.5) * 0.01), usd: Math.round(5000 + Math.pow(cr(), 3) * 900000) }); } return out; })();
  M.lsHistory = (function () { const out = []; let g = 1.05, ta = 1.3, tp = 1.6; for (let i = 72; i >= 0; i--) { g += (cr() - 0.5) * 0.06; ta += (cr() - 0.5) * 0.08; tp += (cr() - 0.5) * 0.1; out.push({ time: new Date(CG.NOW - i * 3600000).toISOString(), global: +g.toFixed(2), topAccounts: +ta.toFixed(2), topPositions: +tp.toFixed(2) }); } return out; })();
  M.oiHistory = (function () { const out = []; let oi = 58e9, px = 76500; for (let i = 96; i >= 0; i--) { oi *= 1 + (cr() - 0.5) * 0.03; px *= 1 + (cr() - 0.49) * 0.02; out.push({ time: new Date(CG.NOW - i * 3600000).toISOString(), oi: Math.round(oi), price: +px.toFixed(0) }); } return out; })();
  M.fundingHistory = (function () { const out = []; let f = 0.01; for (let i = 96; i >= 0; i--) { f += (cr() - 0.5) * 0.006; out.push({ time: new Date(CG.NOW - i * 28800000).toISOString(), funding: +f.toFixed(4), oiWeighted: +(f * 0.9).toFixed(4) }); } return out; })();
  M.priceHistory = function (symbol, n, seed) { const c = M.coins.find((x) => x.symbol === symbol) || M.coins[0]; const r = rng(seed || symbol.length * 131); const out = []; let p = c.price * 0.92; for (let i = n - 1; i >= 0; i--) { const o = p; p *= 1 + (r() - 0.49) * 0.03; out.push({ time: new Date(CG.NOW - i * 3600000).toISOString(), open: o, close: p, high: Math.max(o, p) * (1 + r() * 0.01), low: Math.min(o, p) * (1 - r() * 0.01), volume: c.volume24h / 24 * (0.5 + r()) }); } const k = c.price / out[out.length - 1].close; out.forEach((x) => { x.open *= k; x.close *= k; x.high *= k; x.low *= k; }); return out; };
  M.whaleAlerts = (function () { const out = []; for (let i = 0; i < 14; i++) { const long = cr() > 0.5; const sym = ['BTC', 'ETH', 'SOL', 'HYPE'][Math.floor(cr() * 4)]; out.push({ time: new Date(CG.NOW - i * 420000 * (1 + cr())).toISOString(), wallet: '0x' + Math.floor(cr() * 0xfffff).toString(16).padStart(5, '0') + '…' + Math.floor(cr() * 0xfff).toString(16), symbol: sym, side: long ? 'Long' : 'Short', action: cr() > 0.4 ? 'opened' : 'closed', value: Math.round(1e6 + cr() * 18e6), entry: sym === 'BTC' ? 79521 * (1 + (cr() - 0.5) * 0.02) : sym === 'ETH' ? 2447 * (1 + (cr() - 0.5) * 0.02) : 148 * (1 + (cr() - 0.5) * 0.03), leverage: [5, 10, 20, 25, 40][Math.floor(cr() * 5)] }); } return out; })();
  M.whalePositions = M.whaleAlerts.slice(0, 10).map((w, i) => ({ wallet: w.wallet, symbol: w.symbol, side: w.side, position: w.value, entry: w.entry, mark: w.entry * (1 + (cr() - 0.5) * 0.01), liqPrice: w.side === 'Long' ? w.entry * (1 - 1 / w.leverage) : w.entry * (1 + 1 / w.leverage), upnl: Math.round((cr() - 0.45) * 800000), leverage: w.leverage }));
  M.largeOrders = (function () { const out = []; for (let i = 0; i < 10; i++) { out.push({ time: new Date(CG.NOW - i * 600000 * (1 + cr())).toISOString(), exchange: 'Binance', symbol: 'BTCUSDT', side: cr() > 0.5 ? 'Buy' : 'Sell', price: 79521 * (1 + (cr() - 0.5) * 0.03), value: Math.round(2e6 + cr() * 25e6), status: cr() > 0.3 ? 'placed' : 'filled' }); } return out; })();
  M.whaleIndex = (function () { const out = []; let v = 48; for (let i = 72; i >= 0; i--) { v = Math.max(5, Math.min(95, v + (cr() - 0.5) * 8)); out.push({ time: new Date(CG.NOW - i * 3600000).toISOString(), value: Math.round(v) }); } return out; })();
  M.global = { totalMarketCap: 2.81e12, btcDominance: 55.9, ethDominance: 10.5, totalOi: 62.4e9, totalVol24h: 181e9, liq24h: 214e6, longLiq24h: 132e6, shortLiq24h: 82e6, topLiqCoin: 'BTC', altSeason: 34, avgRsi: 46, gold: 3421.5, goldChg: 0.42, dxy: 101.2, dxyChg: -0.18, btcExchangeBalance: 2.31e6 };
  M.cycle = { ahr999: 0.86, puell: 1.12, piCycle: { ma111: 78120, ma350x2: 121400 }, twoYearMa: 41200, twoYearMaX5: 206000, rainbowBand: 'Accumulate' };
  M.cycleHistory = (function () { const out = []; let a = 0.7, p = 1.0, px = 60000; for (let i = 180; i >= 0; i--) { a += (cr() - 0.48) * 0.05; p += (cr() - 0.5) * 0.06; px *= 1 + (cr() - 0.49) * 0.012; out.push({ date: new Date(CG.NOW - i * 86400000).toISOString().slice(0, 10), ahr999: +Math.max(0.2, a).toFixed(2), puell: +Math.max(0.3, p).toFixed(2), price: Math.round(px), ma111: Math.round(px * 0.98), ma350x2: Math.round(px * 1.5), ma2y: Math.round(px * 0.55), ma2yX5: Math.round(px * 2.75) }); } return out; })();
  M.coinbasePremium = (function () { const out = []; for (let i = 48; i >= 0; i--) out.push({ time: new Date(CG.NOW - i * 3600000).toISOString(), premium: +((cr() - 0.45) * 60).toFixed(1) }); return out; })();
  M.fundingArb = [['BTC', 'Binance', 'Bybit', 0.0121, -0.0042], ['ETH', 'OKX', 'Binance', 0.018, 0.002], ['SOL', 'Bybit', 'Hyperliquid', 0.035, 0.004], ['DOGE', 'Binance', 'OKX', 0.052, 0.011], ['XRP', 'Bitget', 'Binance', 0.021, -0.003]].map(([sym, longLeg, shortLeg, hi, lo]) => ({ symbol: sym, longLeg: longLeg + ' ' + lo.toFixed(4) + '%', shortLeg: shortLeg + ' ' + hi.toFixed(4) + '%', spread: +(hi - lo).toFixed(4), estApr: +((hi - lo) * 3 * 365).toFixed(1), minOi: Math.round(20e6 + cr() * 300e6) }));
  M.optionsByExchange = [['Deribit', 0.78], ['OKX', 0.08], ['Binance', 0.07], ['Bybit', 0.05], ['Delta', 0.02]].map(([name, share]) => ({ exchange: name, oiUsd: 31.5e9 * share, share, oiChg24: +((cr() - 0.45) * 6).toFixed(2), volume24h: 2.9e9 * share * (0.7 + cr() * 0.6), volChg24: +((cr() - 0.5) * 30).toFixed(2) }));
  M.optionsExpiries = ['12SEP26', '19SEP26', '26SEP26', '31OCT26', '28NOV26', '26DEC26', '27MAR27'].map((e, i) => ({ expiry: e, callOi: Math.round(40000 + cr() * 90000), putOi: Math.round(30000 + cr() * 80000), maxPain: 76000 + i * 1500 + Math.round(cr() * 4) * 500 }));
  // ---------- helpers: DOM ----------
  CG.h = (html) => { const t = document.createElement('template'); t.innerHTML = html.trim(); return t.content.firstElementChild; };
  CG.esc = (s) => String(s == null ? '' : s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  CG.$ = (sel, root) => (root || document).querySelector(sel);
  CG.$$ = (sel, root) => Array.from((root || document).querySelectorAll(sel));
  CG.delegate = (root, event, sel, fn) => root.addEventListener(event, (e) => { const t = e.target.closest(sel); if (t && root.contains(t)) fn(e, t); });
  // ---------- toast ----------
  CG.toast = function (o) { if (typeof o === 'string') o = { title: o }; let host = CG.$('.cg-toasts'); if (!host) { host = CG.h('<div class="cg-toasts"></div>'); document.body.appendChild(host); } const el = CG.h('<div class="cg-toast ' + (o.variant || '') + '"><b>' + CG.esc(o.title || '') + '</b>' + (o.description ? '<span>' + CG.esc(o.description) + '</span>' : '') + '</div>'); host.appendChild(el); setTimeout(() => { el.style.opacity = '0'; el.style.transition = 'opacity .3s'; setTimeout(() => el.remove(), 300); }, o.duration || 3200); return el; };
  // ---------- modal ----------
  const modalStack = [];
  CG.modal = {
    open(content, opts) {
      opts = opts || {}; const ov = CG.h('<div class="cg-overlay" role="dialog" aria-modal="true"></div>'); const box = CG.h('<div class="cg-dialog ' + (opts.size || '') + '"></div>');
      let contentEl = typeof content === 'string' ? CG.h('<div>' + content + '</div>') : content; const placeholder = document.createComment('cg-modal-placeholder'); if (contentEl.parentNode) contentEl.parentNode.insertBefore(placeholder, contentEl);
      if (opts.title) box.appendChild(CG.h('<div class="cg-dialog-head"><div><div class="cg-dialog-title">' + CG.esc(opts.title) + '</div>' + (opts.description ? '<div class="cg-dialog-desc">' + CG.esc(opts.description) + '</div>' : '') + '</div><button class="cg-dialog-close" aria-label="Close" data-cg-close>✕</button></div>'));
      else if (!opts.noClose) box.appendChild(CG.h('<div style="position:absolute;right:10px;top:10px;z-index:2"><button class="cg-dialog-close" aria-label="Close" data-cg-close>✕</button></div>'));
      box.style.position = 'relative'; contentEl.hidden = false; contentEl.style.display = ''; box.appendChild(contentEl); ov.appendChild(box); document.body.appendChild(ov); document.body.style.overflow = 'hidden';
      const h = { ov, box, contentEl, placeholder, opts, close: (result) => CG.modal.close(h, result) };
      ov.addEventListener('click', (e) => { if (e.target === ov && !opts.persistent) h.close(); if (e.target.closest('[data-cg-close]')) h.close(); });
      modalStack.push(h); return h;
    },
    close(h, result) { if (!h) h = modalStack[modalStack.length - 1]; if (!h) return; modalStack.splice(modalStack.indexOf(h), 1); if (h.placeholder.parentNode) { h.contentEl.hidden = true; h.placeholder.parentNode.replaceChild(h.contentEl, h.placeholder); } h.ov.remove(); if (!modalStack.length) document.body.style.overflow = ''; if (h.opts.onClose) h.opts.onClose(result); },
    closeAll() { while (modalStack.length) CG.modal.close(); },
    confirm(o) { return new Promise((res) => { const el = CG.h('<div><div class="cg-dialog-head"><div><div class="cg-dialog-title">' + CG.esc(o.title || 'Are you sure?') + '</div>' + (o.description ? '<div class="cg-dialog-desc">' + CG.esc(o.description) + '</div>' : '') + '</div></div>' + (o.body ? '<div class="cg-dialog-body">' + o.body + '</div>' : '') + '<div class="cg-dialog-foot"><button class="btn btn-outline" data-x="0">' + CG.esc(o.cancelText || 'Cancel') + '</button><button class="btn ' + (o.variant === 'destructive' ? 'btn-destructive' : 'btn-primary') + '" data-x="1">' + CG.esc(o.confirmText || 'Confirm') + '</button></div></div>'); const h = CG.modal.open(el, { size: 'sm', noClose: true, onClose: (r) => res(!!r) }); el.addEventListener('click', (e) => { const b = e.target.closest('[data-x]'); if (b) h.close(b.dataset.x === '1'); }); }); }
  };
  document.addEventListener('keydown', (e) => { if (e.key === 'Escape' && modalStack.length && !modalStack[modalStack.length - 1].opts.persistent) CG.modal.close(); });
  // ---------- dropdown menu ----------
  CG.menu = function (anchor, html, opts) { CG.menu.closeAll(); const m = CG.h('<div class="menu">' + html + '</div>'); document.body.appendChild(m); const r = anchor.getBoundingClientRect(); const w = m.offsetWidth; let left = (opts && opts.align === 'left') ? r.left : r.right - w; left = Math.max(8, Math.min(left, window.innerWidth - w - 8)); m.style.left = left + window.scrollX + 'px'; m.style.top = r.bottom + 6 + window.scrollY + 'px'; const off = (e) => { if (!m.contains(e.target) && e.target !== anchor && !anchor.contains(e.target)) { m.remove(); document.removeEventListener('mousedown', off); } }; setTimeout(() => document.addEventListener('mousedown', off), 0); m.addEventListener('click', (e) => { if (e.target.closest('.menu-item')) { m.remove(); document.removeEventListener('mousedown', off); } }); return m; };
  CG.menu.closeAll = () => CG.$$('.menu').forEach((m) => m.remove());
  // ---------- theme ----------
  CG.theme = { get: () => (document.documentElement.classList.contains('dark') ? 'dark' : 'light'), set(t) { document.documentElement.classList.toggle('dark', t === 'dark'); try { localStorage.setItem('cg-v2-theme', t); } catch (e) { } CG.emit('theme', t); }, toggle() { CG.theme.set(CG.theme.get() === 'dark' ? 'light' : 'dark'); } };
  try { const t = localStorage.getItem('cg-v2-theme'); CG.theme.set(t || 'dark'); } catch (e) { CG.theme.set('dark'); }
  // ---------- auth ----------
  CG.auth = { login(email) { st.loggedIn = true; if (email) M.user.email = email; CG.saveState(); CG.emit('auth', true); }, logout() { st.loggedIn = false; CG.saveState(); CG.emit('auth', false); CG.navigate('/'); }, isAdmin: () => st.loggedIn && st.role === 'admin' };
  // ---------- router ----------
  const screens = {}; const handlers = {}; const inited = new Set();
  CG.register = function (route, h) { handlers[route] = Object.assign(handlers[route] || {}, h); };
  function matchRoute(pattern, path) { const pp = pattern.split('/').filter(Boolean), sp = path.split('/').filter(Boolean); if (pattern === '*') return {}; if (pp.length !== sp.length) return null; const params = {}; for (let i = 0; i < pp.length; i++) { if (pp[i][0] === ':') params[pp[i].slice(1)] = decodeURIComponent(sp[i]); else if (pp[i] !== sp[i]) return null; } return params; }
  CG.parseHash = function () { let h = location.hash.replace(/^#/, '') || '/'; if (h[0] !== '/') h = '/' + h; const [path, q] = h.split('?'); const query = {}; (q || '').split('&').filter(Boolean).forEach((kv) => { const [k, v] = kv.split('='); query[decodeURIComponent(k)] = decodeURIComponent(v || ''); }); return { path: path.replace(/\/+$/, '') || '/', query }; };
  CG.navigate = function (path, opts) { if (!path.startsWith('/')) path = '/' + path; const target = '#' + path; if (location.hash === target) { CG.route(); return; } if (opts && opts.replace) location.replace(target); else location.hash = target; };
  CG.current = { path: '/', query: {}, params: {} };
  CG.route = function () {
    const { path, query } = CG.parseHash(); let best = null;
    CG.$$('section.screen').forEach((sec) => { const pat = sec.dataset.route; const params = matchRoute(pat, path); if (params && (!best || pat !== '*')) { if (!best || best.pat === '*') best = { sec, pat, params }; } });
    if (!best) { const nf = CG.$$('section.screen').find((s) => s.dataset.route === '*'); best = { sec: nf, pat: '*', params: {} }; }
    if (!best.sec) return;
    const auth = best.sec.dataset.auth; if (auth && !st.loggedIn) { CG.navigate('/auth?next=' + encodeURIComponent(path), { replace: true }); return; } if (auth === 'admin' && !CG.auth.isAdmin()) { CG.navigate('/analyse', { replace: true }); return; }
    if (best.sec.dataset.redirect) { CG.navigate(best.sec.dataset.redirect, { replace: true }); return; }
    const prev = CG.$('section.screen.active'); if (prev && prev !== best.sec) { prev.classList.remove('active'); const ph = handlers[prev.dataset.route]; if (ph && ph.hide) { try { ph.hide(prev); } catch (e) { console.error(e); } } }
    CG.current = { path, query, params: best.params, route: best.pat }; CG.menu.closeAll();
    best.sec.classList.add('active'); document.title = (best.sec.dataset.title ? best.sec.dataset.title + ' · ' : '') + 'HapieCoin';
    // chrome placeholders
    CG.$$('[data-cg]', best.sec).forEach((el) => { if (el.dataset.cgDone) return; const fn = CG.chrome[el.dataset.cg]; if (typeof fn === 'function') { try { fn(el, best.sec); el.dataset.cgDone = '1'; } catch (e) { console.error('chrome', el.dataset.cg, e); } } });
    const keys = Object.keys(handlers).filter((k) => k === best.pat || k.startsWith(best.pat + ':'));
    keys.forEach((k) => { const h = handlers[k]; if (!inited.has(k) && h.init) { try { h.init(best.sec, best.params, query); } catch (e) { console.error('init', k, e); } inited.add(k); } if (h.show) { try { h.show(best.sec, best.params, query); } catch (e) { console.error('show', k, e); } } });
    CG.$$('[data-cg]', best.sec).forEach((el) => { const fn = CG.chrome[el.dataset.cg + ':update']; if (typeof fn === 'function') { try { fn(el, best.sec); } catch (e) { } } });
    window.scrollTo(0, 0); CG.emit('route', CG.current);
  };
  window.addEventListener('hashchange', CG.route);
  document.addEventListener('click', (e) => { const a = e.target.closest('a[href^="#/"]'); if (a) { e.preventDefault(); CG.navigate(a.getAttribute('href').slice(1)); } const b = e.target.closest('[data-nav]'); if (b) { e.preventDefault(); CG.navigate(b.dataset.nav); } });
  // ---------- chrome (shared layout pieces) : overridable by area files ----------
  CG.chrome = CG.chrome || {};
  CG.chrome['app-header'] = function (el) { el.innerHTML = '<header class="cg-header"><a href="#/analyse" class="cg-logo"><i>C</i>HapieCoin</a><nav class="cg-nav flex gap-1 ml-auto"><a href="#/analyse">Analyse</a><a href="#/analytics">Market Analytics</a><a href="#/subscription">My Subscription</a><a href="#/referrals">My Referrals</a><a href="#/admin/users">Admin</a></nav><button class="btn btn-ghost btn-icon" data-theme-toggle title="Toggle theme">◐</button><button class="btn btn-outline btn-sm" data-logout>Logout</button></header>'; el.querySelector('[data-theme-toggle]').onclick = () => CG.theme.toggle(); el.querySelector('[data-logout]').onclick = () => CG.auth.logout(); };
  CG.chrome['footer'] = function (el) { el.innerHTML = '<footer class="cg-footer"><div class="container flex justify-between flex-wrap gap-4"><span>© ' + CG.NOW.getFullYear() + ' HapieCoin. All rights reserved.</span><span class="flex gap-4"><a href="#/privacy">Privacy Policy</a><a href="#/terms">Terms of Service</a><a href="#/disclaimer">Disclaimer</a></span></div></footer>'; };
  // ---------- live price simulation ----------
  CG.live = { running: true, tick() { Object.values(CG.ASSETS).forEach((A) => { const r = Math.random(); const d = (r - 0.5) * A.price * 0.0006; A.prev = A.price; A.price = +(A.price + d).toFixed(A.price > 1000 ? 1 : 2); }); Object.keys(chainCache).forEach((k) => delete chainCache[k]); CG.emit('tick', CG.ASSETS); } };
  setInterval(() => { if (CG.live.running && st.liveFeed) CG.live.tick(); }, 2500);
  // ---------- boot ----------
  CG.boot = function () { if (!location.hash) location.replace('#/'); CG.route(); };
  document.addEventListener('DOMContentLoaded', () => setTimeout(CG.boot, 0));
})();
