  // ======================================================================
  // SELECT OPTION FROM CHAIN (modal, size xl) · Calls | Strike | Puts mirrored outward
  // ======================================================================
  T.openChainModal = function (opts) {
    opts = opts || {}; const asset = opts.asset || AN.asset; let expiry = opts.expiry || AN.expiry || ST.expiry; if (!CG.EXPIRIES.includes(expiry)) expiry = ST.expiry; let live = ST.liveFeed !== false; const max = opts.max != null ? opts.max : remainingSlots(); const sel = []; const cols = { delta: true, oi: true, bid: true, mark: true };
    const el = h('<div class="trd-dlg trd-chain-dlg' + (S.density === 'compact' ? ' trd-compact' : '') + '"></div>');
    const off = CG.on('tick', () => { if (live) renderBody(true); renderHead(); });
    const hd = CG.modal.open(el, { size: 'xl', noClose: true, onClose: () => { off(); S.chain = null; } });
    S.chain = { close: () => hd.close(), select: toggle, selected: sel, setExpiry: (e) => { expiry = e; renderAll(); } };
    function key(type, strike, exp) { return type + ':' + strike + ':' + exp; }
    function toggle(type, side, strike) { const k = key(type, strike, expiry); const i = sel.findIndex((x) => x.key === k); if (i >= 0) { if (sel[i].side === side) sel.splice(i, 1); else sel[i].side = side; } else { if (max != null && sel.length >= max) { CG.toast({ title: 'Maximum legs reached', description: 'Maximum ' + plural(max, 'leg') + ' can be selected', variant: 'destructive' }); return; } const q = CG.quote(asset, expiry, strike, type); sel.push({ key: k, type, side, strike, expiry, price: q.mark, lots: 1, unit: 'LOTS' }); } renderBody(); renderSel(); }
    function renderHead() { const hh = el.querySelector('[data-chain-head]'); const html = '<div class="trd-chain-ico">' + I.bolt + '</div><div><div class="cg-dialog-title">' + (opts.title || 'Select Option from Chain') + '</div><div class="cg-dialog-desc"><span class="trd-tag">' + esc(asset) + '</span><span>Spot <b class="mono">' + money(spot(asset), ST.currency === 'INR' ? 0 : 1) + '</b></span><span class="micro">·</span><span class="micro">' + expPretty(expiry) + ' · ' + dteOf(expiry) + 'd</span>' + (max != null ? '<span class="trd-tag">max ' + plural(max, 'leg') + '</span>' : '') + '</div></div><button class="cg-dialog-close" aria-label="Close" data-cg-close>✕</button>'; if (hh) hh.innerHTML = html; return '<div class="trd-chain-head" data-chain-head>' + html + '</div>'; }
    function renderExp() { return '<div class="trd-exp-row"><button class="trd-icon-btn" data-act="exp-l" title="Previous">' + I.chevL + '</button><div class="trd-exp-strip" data-strip>' + CG.EXPIRIES.map((e) => '<button class="trd-exp' + (e === expiry ? ' active' : '') + '" data-act="exp" data-exp="' + e + '"><span>' + expPretty(e) + '</span><em>' + dteOf(e) + 'd</em></button>').join('') + '</div><button class="trd-icon-btn" data-act="exp-r" title="Next">' + I.chevR + '</button><button class="trd-livebtn' + (live ? '' : ' off') + '" data-act="live" title="' + (live ? 'Live · click to freeze' : 'Static · click to enable live prices') + '">' + I.bolt + ' ' + (live ? 'Live' : 'Static') + '</button><button class="trd-icon-btn" data-act="cols" title="Column settings">' + I.gear + '</button></div>'; }
    function bodyHtml() {
      const ch = CG.chain(asset, expiry); const maxOi = Math.max(...ch.rows.map((r) => Math.max(r.call.oi, r.put.oi)));
      const px = (side, q, itm, kind) => { if (!cols[kind]) return ''; const p = kind === 'mark' ? q.mark : q.bid, iv = kind === 'mark' ? q.markIv : q.bidIv; return '<td class="' + side + (itm ? ' itm' : '') + '"><span class="px">' + F.num(p, 1) + '</span><span class="iv">' + iv.toFixed(1) + '%</span></td>'; };
      const oi = (side, q, itm) => cols.oi ? '<td class="' + side + ' oi' + (itm ? ' itm' : '') + '">' + F.compact(q.oi) + '<i style="width:' + Math.round(q.oi / maxOi * 44) + 'px"></i></td>' : '';
      const dl = (side, q, itm) => cols.delta ? '<td class="' + side + ' dl' + (itm ? ' itm' : '') + '">' + q.delta.toFixed(2) + '</td>' : '';
      const act = (type, strike) => { const k = key(type, strike, expiry); const s = sel.find((x) => x.key === k); return '<td class="act"><button class="trd-bs b' + (s && s.side === 'BUY' ? ' on' : '') + '" data-act="bs" data-type="' + type + '" data-side="BUY" data-strike="' + strike + '" title="Buy ' + type + ' ' + strike + '">B</button><button class="trd-bs s' + (s && s.side === 'SELL' ? ' on' : '') + '" data-act="bs" data-type="' + type + '" data-side="SELL" data-strike="' + strike + '" title="Sell ' + type + ' ' + strike + '">S</button></td>'; };
      return ch.rows.map((r) => '<tr class="trd-cr' + (r.atm ? ' atm' : '') + '" data-strike="' + r.strike + '">' + dl('c', r.call, r.itmCall) + oi('c', r.call, r.itmCall) + px('c', r.call, r.itmCall, 'bid') + px('c', r.call, r.itmCall, 'mark') + act('CALL', r.strike) + '<td class="strk">' + r.strike.toLocaleString('en-US') + (r.atm ? '<small>ATM</small>' : '') + '</td>' + act('PUT', r.strike) + px('p', r.put, r.itmPut, 'mark') + px('p', r.put, r.itmPut, 'bid') + oi('p', r.put, r.itmPut) + dl('p', r.put, r.itmPut) + '</tr>').join('');
    }
    function tableHtml() { const n = ['delta', 'oi', 'bid', 'mark'].filter((k) => cols[k]).length; const th = (k, lbl, p) => cols[k] ? '<th' + (p ? ' class="p"' : '') + '>' + lbl + '</th>' : ''; return '<div class="trd-chain-wrap" data-wrap><table class="trd-chain"><thead><tr class="grp"><th class="calls" colspan="' + (n + 1) + '">Calls<em>ITM shaded · OI bars grow toward the strike</em></th><th class="strk">' + expPretty(expiry) + '</th><th class="puts" colspan="' + (n + 1) + '"><em style="margin:0 8px 0 0">Δ per contract</em>Puts</th></tr><tr class="cols">' + th('delta', 'Δ') + th('oi', 'OI') + th('bid', 'Bid <em>/IV</em>') + th('mark', 'Mark <em>/IV</em>') + '<th></th><th class="strk">Strike</th><th class="p"></th>' + th('mark', 'Mark <em>/IV</em>', true) + th('bid', 'Bid <em>/IV</em>', true) + th('oi', 'OI', true) + th('delta', 'Δ', true) + '</tr></thead><tbody data-body>' + bodyHtml() + '</tbody></table></div>'; }
    function renderBody(keep) { const body = el.querySelector('[data-body]'); if (!body) return; const wrap = el.querySelector('[data-wrap]'); const top = wrap ? wrap.scrollTop : 0; body.innerHTML = bodyHtml(); if (wrap && keep !== false) wrap.scrollTop = top; }
    function selHtml() { if (!sel.length) return ''; return '<div class="trd-sel" data-sel><div class="trd-sel-head"><b>' + plural(sel.length, 'leg') + ' selected</b>' + (max != null ? '<span class="micro">of ' + max + ' max</span>' : '') + '<button class="btn btn-ghost btn-xs ml-auto" data-act="sel-clear">' + I.x + ' Clear</button></div>' + sel.map((s, i) => '<div class="trd-sel-row" data-i="' + i + '">' + sideBadge(s.side) + typeBadge(s.type) + '<b>' + s.strike.toLocaleString('en-US') + '</b><span class="text-muted">' + expPretty(s.expiry) + '</span><span>' + F.num(s.price, 1) + '</span><span class="micro" style="margin-left:auto">Lots</span>' + stepper(s.lots, 'sel-qty') + '<button class="trd-icon-btn danger" data-act="sel-x" title="Remove">' + I.x + '</button></div>').join('') + '</div>'; }
    function footHtml() { return '<div class="trd-chain-foot"><span>Click <b class="text-profit">B</b> to buy or <b class="text-loss">S</b> to sell · select multiple legs · <span class="micro">' + CG.chain(asset, expiry).rows.length + ' strikes</span></span><div class="flex gap-2">' + (sel.length ? '<button class="btn btn-outline btn-sm" data-act="sel-clear">Clear</button><button class="btn btn-primary btn-sm" data-act="add">' + I.plus + ' Add ' + plural(sel.length, 'leg') + '</button>' : '') + '<button class="btn btn-outline btn-sm" data-act="close">Close</button></div></div>'; }
    function renderSel() { let s = el.querySelector('[data-sel]'); const html = selHtml(); if (s) { if (html) s.outerHTML = html; else s.remove(); } else if (html) { el.querySelector('[data-wrap]').insertAdjacentHTML('afterend', html); } el.querySelector('.trd-chain-foot').outerHTML = footHtml(); }
    function renderAll() { el.innerHTML = renderHead() + renderExp() + tableHtml() + selHtml() + footHtml(); scrollAtm(); const strip = el.querySelector('[data-strip]'); const a = strip && strip.querySelector('.trd-exp.active'); if (a) strip.scrollLeft = Math.max(0, a.offsetLeft - 60); }
    function scrollAtm() { const wrap = el.querySelector('[data-wrap]'); const atm = el.querySelector('tr.atm'); if (wrap && atm) wrap.scrollTop = Math.max(0, atm.offsetTop - wrap.clientHeight / 2 + 20); }
    function finish() { if (!sel.length) return; const legs = sel.map((s) => ({ type: s.type, side: s.side, strike: s.strike, expiry: s.expiry, lots: s.lots, price: s.price, unit: s.unit })); if (opts.onAdd) { opts.onAdd(legs, hd); return; } const added = T.addLegs(legs); if (added.length) hd.close(); }
    CG.delegate(el, 'click', '[data-act]', (e, t) => { const act = t.dataset.act; if (act === 'bs') toggle(t.dataset.type, t.dataset.side, +t.dataset.strike); else if (act === 'exp') { expiry = t.dataset.exp; renderAll(); } else if (act === 'exp-l' || act === 'exp-r') { const strip = el.querySelector('[data-strip]'); strip.scrollLeft += act === 'exp-l' ? -220 : 220; } else if (act === 'live') { live = !live; el.querySelector('[data-act="live"]').outerHTML = '<button class="trd-livebtn' + (live ? '' : ' off') + '" data-act="live" title="' + (live ? 'Live · click to freeze' : 'Static · click to enable live prices') + '">' + I.bolt + ' ' + (live ? 'Live' : 'Static') + '</button>'; CG.toast({ title: live ? 'Live' : 'Static', description: live ? 'Chain prices update with the live feed' : 'Chain prices frozen · click to enable live prices' }); } else if (act === 'cols') { const m = CG.menu(t, '<div class="menu-label">Column settings</div>' + [['delta', 'Δ (delta)'], ['oi', 'OI'], ['bid', 'Bid (Price/IV)'], ['mark', 'Mark (Price/IV)']].map(([k, l]) => '<label class="menu-item"><input type="checkbox" class="checkbox" data-col="' + k + '"' + (cols[k] ? ' checked' : '') + '> ' + l + '</label>').join('')); m.addEventListener('change', (ev) => { const c = ev.target.closest('[data-col]'); if (!c) return; cols[c.dataset.col] = c.checked; const wrap = el.querySelector('[data-wrap]'); wrap.outerHTML = tableHtml(); scrollAtm(); }); } else if (act === 'sel-clear') { sel.length = 0; renderBody(); renderSel(); } else if (act === 'sel-x') { const i = +t.closest('[data-i]').dataset.i; sel.splice(i, 1); renderBody(); renderSel(); } else if (act === 'sel-qty-inc' || act === 'sel-qty-dec') { const s = sel[+t.closest('[data-i]').dataset.i]; if (s) { s.lots = Math.max(1, s.lots + (act === 'sel-qty-inc' ? 1 : -1)); renderSel(); } } else if (act === 'add') finish(); else if (act === 'close') hd.close(); });
    el.addEventListener('change', (e) => { const t = e.target; const row = t.closest('[data-i]'); if (!row) return; const s = sel[+row.dataset.i]; if (!s) return; if (t.dataset.act === 'sel-qty') { s.lots = Math.max(1, Math.round(+t.value || 1)); t.value = s.lots; } });
    renderAll();
    return hd;
  };
  // ======================================================================
  // ADD FUTURES CONTRACT
  // ======================================================================
  T.openFutureDialog = function (opts) {
    opts = opts || {}; const asset = opts.asset || AN.asset; const A = CG.ASSETS[asset]; let side = 'BUY', expiry = 'PERP', lots = 1;
    const el = h('<div class="trd-dlg"><div class="cg-dialog-body"><div class="field"><label class="label">USD Future</label><div class="trd-fut-sym">' + typeBadge('FUTURE') + '<span data-sym>' + esc(A.futSymbol) + '</span><span class="micro" data-symsub>Perpetual</span><span class="ml-auto" data-px>' + F.num(spot(asset), 1) + '</span><span class="trd-live-dot" title="Live price from Delta Exchange"></span></div></div><div class="field"><label class="label">Side</label><div class="trd-sidebtns"><button class="trd-sidebtn buy active" data-side="BUY">Buy future</button><button class="trd-sidebtn sell" data-side="SELL">Sell future</button></div></div><div class="grid grid-2 gap-3"><div class="field"><label class="label">Expiry</label><select class="select" data-exp><option value="PERP">Perpetual</option>' + CG.EXPIRIES.map((e) => '<option value="' + e + '">' + expPretty(e) + ' · ' + dteOf(e) + 'd</option>').join('') + '</select></div><div class="field"><label class="label">Quantity (lots)</label>' + stepper(1, 'lots') + '<div class="hint">1 lot = ' + lotOf(asset) + ' ' + esc(asset) + '</div></div></div><div class="trd-kv"><span>Price</span><b data-px2>' + money(spot(asset)) + '</b><span>Notional</span><b data-notional>' + money(spot(asset) * lotOf(asset)) + '</b><span>Margin est. (5%)</span><b data-margin>' + money(spot(asset) * lotOf(asset) * 0.05) + '</b></div></div><div class="cg-dialog-foot"><button class="btn btn-outline" data-cg-close>Cancel</button><button class="btn btn-primary" data-add>' + I.plus + ' Add</button></div></div>');
    const upd = () => { const p = spot(asset); CG.$$('[data-px]', el).forEach((n) => { n.textContent = F.num(p, 1); }); el.querySelector('[data-px2]').textContent = money(p); el.querySelector('[data-notional]').textContent = money(p * lotOf(asset) * lots); el.querySelector('[data-margin]').textContent = money(p * lotOf(asset) * lots * 0.05); };
    const off = CG.on('tick', upd);
    const hd = CG.modal.open(el, { title: 'Add Futures Contract', description: 'Add a ' + asset + ' USD futures leg at the live price', onClose: off });
    el.addEventListener('click', (e) => { const b = e.target.closest('[data-side]'); if (b) { side = b.dataset.side; CG.$$('[data-side]', el).forEach((x) => x.classList.toggle('active', x === b)); } const st = e.target.closest('[data-act="lots-inc"],[data-act="lots-dec"]'); if (st) { lots = Math.max(1, lots + (st.dataset.act === 'lots-inc' ? 1 : -1)); el.querySelector('[data-act="lots"]').value = lots; upd(); } if (e.target.closest('[data-add]')) { const leg = { type: 'FUTURE', side, expiry, lots, price: spot(asset), asset }; if (opts.onAdd) { opts.onAdd(leg, hd); return; } const added = T.addLeg(leg); if (added) hd.close(); } });
    el.addEventListener('change', (e) => { const t = e.target; if (t.hasAttribute('data-exp')) { expiry = t.value; el.querySelector('[data-sym]').textContent = A.futSymbol + (expiry === 'PERP' ? '' : '-' + expiry); el.querySelector('[data-symsub]').textContent = expiry === 'PERP' ? 'Perpetual' : 'Expires ' + expPretty(expiry); } if (t.dataset.act === 'lots') { lots = Math.max(1, Math.round(+t.value || 1)); t.value = lots; upd(); } });
    return hd;
  };
  // ======================================================================
  // SAVE DIALOG
  // ======================================================================
  T.openSaveDialog = function (mode, cb) {
    mode = mode === 'trade' ? 'trade' : 'draft';
    if (!AN.legs.length) { CG.toast({ title: 'No legs', description: 'Add at least one leg', variant: 'destructive' }); return null; }
    const el = h('<div class="trd-dlg" data-tour="save-dialog"><div class="cg-dialog-body"><div class="field"><label class="label">Strategy name</label><input class="input" data-name placeholder="Strategy name..." value="' + esc(AN.name || '') + '" maxlength="80"><div class="trd-err" data-err hidden>Strategy name is required</div><div class="hint">' + (mode === 'trade' ? 'Name your strategy · it will be saved before trading' : 'Press Enter to save, Escape to cancel') + '</div></div><div class="trd-b-net" style="padding:0"><span class="trd-tag">' + esc(AN.asset) + '</span><span>' + plural(AN.legs.length, 'leg') + '</span><span>' + esc(guessTemplate(AN.legs)) + '</span></div></div><div class="cg-dialog-foot"><button class="btn btn-outline" data-cg-close>Cancel</button><button class="btn btn-primary" data-save data-tour="save-button">' + (mode === 'trade' ? 'Save &amp; continue' : 'Save draft') + '</button></div></div>');
    const hd = CG.modal.open(el, { title: mode === 'trade' ? 'Enter Strategy Name' : 'Save as Draft', description: mode === 'trade' ? 'Name your strategy' : 'Save the current legs to Draft Strategies' });
    const inp = el.querySelector('[data-name]'); const btn = el.querySelector('[data-save]');
    const doSave = () => { const name = inp.value.trim(); if (!name) { el.querySelector('[data-err]').hidden = false; inp.focus(); return; } btn.disabled = true; btn.textContent = 'Saving...'; const s = T.saveDraft(name); hd.close(); if (cb) cb(s); };
    btn.addEventListener('click', doSave);
    inp.addEventListener('keydown', (e) => { if (e.key === 'Enter') { e.preventDefault(); doSave(); } else if (e.key === 'Escape') { e.preventDefault(); e.stopPropagation(); hd.close(); } });
    inp.addEventListener('input', () => { el.querySelector('[data-err]').hidden = true; });
    setTimeout(() => { inp.focus(); inp.select(); }, 30);
    CG.emit('cg-tour:save-dialog-open');
    return hd;
  };
  // ======================================================================
  // SELECT TRADING MODE (two cards + exchange fee summary) → TRADE PREVIEW → start
  // ======================================================================
  function feeLine(f) { const b = f.broker; return esc(brokerShort(b)) + ' · fee ' + b.feePercentage + '% of notional · cap ' + b.feeCapPercentage + '% of premium' + (b.gstPercentage ? ' · GST ' + b.gstPercentage + '%' : ' · no GST'); }
  T.openTradeMode = function (ctx) {
    ctx = ctx || {}; let mode = ctx.mode === 'live' ? 'live' : 'paper'; const lockLive = !!ctx.batch || ctx.source === 'golive'; if (lockLive) mode = 'live';
    const def = M.brokers.find((b) => b.isDefault) || M.brokers[0]; let brokerId = ctx.brokerId || S.brokerId || (def ? def.id : '');
    const asset = ctx.batch ? ctx.batch[0].asset : ctx.strategy && !ctx.fromBuilder ? ctx.strategy.asset : AN.asset;
    const legs = ctx.batch ? ctx.batch.reduce((a, s) => a.concat(openLegs(s)), []) : ctx.strategy && !ctx.fromBuilder ? openLegs(ctx.strategy) : AN.legs.filter((l) => l.status !== 'SQUARED_OFF');
    if (!legs.length) { CG.toast({ title: 'No legs', description: 'Add at least one leg to trade', variant: 'destructive' }); return null; }
    const el = h('<div class="trd-dlg"></div>');
    const hd = CG.modal.open(el, { title: 'Select Trading Mode', description: ctx.batch ? 'Trade all ' + ctx.batch.length + (ctx.batch.length === 1 ? ' paper strategy' : ' paper strategies') + ' live on the exchange' : 'Choose how you want to trade ' + (ctx.strategy ? '“' + ctx.strategy.name + '”' : 'this strategy') });
    function render() {
      const connected = !!ST.exchangeConnected; const live = mode === 'live'; const f = feeFor(legs, asset, brokerOf(brokerId)); let np = 0; try { np = CG.analyze(legs, asset).netPremium; } catch (e) { }
      el.innerHTML = '<div class="cg-dialog-body"><div class="trd-modes" data-tour="trade-modal"><button class="trd-mode' + (!live ? ' active' : '') + '" data-mode="paper"' + (lockLive ? ' disabled' : '') + '><b>' + modePill('PAPER') + 'Paper<span class="trd-check-ico">' + I.check + '</span></b><small>Simulated positions tracked at live market prices. No real orders are placed.</small><span class="trd-mode-fee">fees simulated · ' + money(f.total) + ' est.</span></button><button class="trd-mode' + (live ? ' active' : '') + '" data-mode="live"><b>' + modePill('LIVE') + 'Live<span class="trd-check-ico">' + I.check + '</span></b><small>Real money. Orders are placed on the exchange at market with real funds.</small><span class="trd-mode-fee">' + (connected ? 'exchange connected' : 'exchange not connected') + ' · ' + money(f.total) + ' fees est.</span></button></div>' +
        '<div class="field"><label class="label">Exchange</label><select class="select" data-broker><option value="">Select exchange...</option>' + M.brokers.map((b) => '<option value="' + b.id + '"' + (b.id === brokerId ? ' selected' : '') + '>' + esc(b.name) + ' · Fee ' + b.feePercentage + '% · GST ' + b.gstPercentage + '% · Cap ' + b.feeCapPercentage + '%</option>').join('') + '</select><div class="trd-err" data-err hidden>Please select an exchange</div></div>' +
        '<div class="trd-feebox"><span class="micro">Fee summary</span><span>' + feeLine(f) + '</span><span>→ est. <b>' + money(f.total) + '</b> for ' + plural(f.legs, 'leg') + ' (' + money(f.fee) + ' fee' + (f.gst ? ' + ' + money(f.gst) + ' GST' : '') + ')</span></div>' +
        '<div class="trd-kv"><span>Legs</span><b>' + legs.length + '</b><span>Asset</span><b>' + esc(ctx.batch ? Array.from(new Set(ctx.batch.map((s) => s.asset))).join(', ') : asset) + '</b><span>Net premium</span><b class="' + (np >= 0 ? 'text-profit' : '') + '">' + (np >= 0 ? 'Credit ' : 'Debit ') + money(Math.abs(np)) + '</b><span>Price mode</span><b>' + (AN.mode === 'custom' && ctx.fromBuilder ? 'Custom (entered prices)' : 'Live (Delta Exchange)') + '</b></div>' +
        (live && !connected ? noteBox('warning', 'Not Connected', 'Connect your exchange in Settings → API Settings to enable live trading', '<button class="btn btn-outline btn-xs mt-2" data-settings>Open API Settings</button>') : '') +
        (live ? noteBox('destructive', 'Real Money Trading', 'Orders will be placed on Delta Exchange with real funds. Prices may differ from estimates. You may lose money.') : noteBox('info', 'Paper Trading', 'Simulated positions tracked with live market prices. No real orders are placed.')) +
        '</div><div class="cg-dialog-foot"><button class="btn btn-outline" data-cg-close>Cancel</button><button class="btn btn-primary" data-go data-tour="trade-confirm-button"' + (live && !connected ? ' disabled title="Connect your exchange first"' : '') + '>' + (live ? 'Continue · Live' : 'Continue · Paper') + ' →</button></div>';
    }
    el.addEventListener('click', (e) => {
      const m = e.target.closest('[data-mode]'); if (m && !m.disabled) { mode = m.dataset.mode; render(); return; }
      if (e.target.closest('[data-settings]')) { if (CG.chrome && typeof CG.chrome.openSettings === 'function') { hd.close(); CG.chrome.openSettings('api'); } else CG.toast({ title: 'API Settings', description: 'Open Settings → API Settings to connect Delta Exchange' }); return; }
      if (e.target.closest('[data-go]')) { const sel = el.querySelector('[data-broker]'); brokerId = sel.value; if (!brokerId) { el.querySelector('[data-err]').hidden = false; return; } if (!quotaOk(mode)) return; S.brokerId = brokerId; renderTicket(); hd.close(); T.openTradePreview(Object.assign({}, ctx, { mode, brokerId, legs })); }
    });
    el.addEventListener('change', (e) => { if (e.target.hasAttribute('data-broker')) { brokerId = e.target.value; S.brokerId = brokerId || S.brokerId; render(); renderTicket(); } });
    render();
    CG.emit('cg-tour:trade-modal-open');
    return hd;
  };
  T.openTradePreview = function (ctx) {
    const live = ctx.mode === 'live'; const asset = ctx.batch ? ctx.batch[0].asset : ctx.strategy && !ctx.fromBuilder ? ctx.strategy.asset : AN.asset; const legs = ctx.legs; const lot = lotOf(asset);
    const useCustom = ctx.fromBuilder && AN.mode === 'custom';
    const priced = legs.map((l) => Object.assign(cloneLeg(l), { price: useCustom ? l.price : (l.status === 'OPEN' && ctx.strategy && !ctx.fromBuilder ? (l.entryPremium != null ? l.entryPremium : l.price) : quoteLeg(l, asset).mark) }));
    let r = null; try { r = CG.analyze(priced, asset); } catch (e) { }
    const np = r ? r.netPremium : 0; const f = feeFor(priced, asset, brokerOf(ctx.brokerId)); const net = np - f.total;
    const el = h('<div class="trd-dlg" data-tour="trade-modal"><div class="cg-dialog-body"><div class="overflow-x-auto"><table class="trd-pv"><thead><tr><th class="l">Side</th><th class="l">Instrument</th><th>Lots</th><th>Price</th><th>Value</th><th>Fee</th></tr></thead><tbody>' + priced.map((l) => { const pf = f.per.find((x) => x.id === l.id) || { fee: 0, gst: 0 }; return '<tr><td class="l">' + sideBadge(l.side) + '</td><td class="l">' + insCell(l, asset) + '</td><td>' + l.lots + '</td><td>' + F.num(l.price, 1) + '</td><td>' + money(l.price * l.lots * lot) + '</td><td class="text-muted">' + money(pf.fee + pf.gst) + '</td></tr>'; }).join('') + '</tbody></table></div>' +
      '<div class="trd-kv mt-3"><span>Net premium</span><b class="' + (np >= 0 ? 'text-profit' : '') + '">' + (np >= 0 ? 'Credit ' : 'Debit ') + money(Math.abs(np)) + '</b><span>Fees · est.<span class="text-2xs text-muted" style="display:block;margin-top:1px">' + feeLine(f) + '</span></span><b>' + money(f.total) + '</b><span class="trd-kv-sum">' + (net >= 0 ? 'You will receive' : 'You will pay') + '</span><b class="trd-kv-sum ' + (net >= 0 ? 'text-profit' : '') + '">' + money(Math.abs(net)) + '</b><span>Current ' + esc(asset) + ' price</span><b>' + money(spot(asset)) + '</b><span>Expected required margin</span><b>' + (r ? money(r.margin) : '—') + '</b>' + (r && isFinite(r.maxLoss) ? '<span>Max loss</span><b class="text-loss">' + money(Math.abs(r.maxLoss)) + '</b>' : '') + (ctx.batch ? '<span>Strategies</span><b>' + ctx.batch.length + '</b>' : '') + '<span>Exchange</span><b>' + esc(brokerName(ctx.brokerId)) + '</b><span>Mode</span><b>' + modePill(live ? 'LIVE' : 'PAPER') + '</b></div>' +
      (live ? noteBox('destructive', '', 'You are about to trade this strategy. Orders will be placed on Delta Exchange. Prices may differ from displayed estimates. Ensure you have sufficient margin.') : noteBox('info', '', 'Paper trade · positions will be tracked at ' + (useCustom ? 'your entered prices' : 'live market prices') + '. No real orders are placed.')) + '</div><div class="cg-dialog-foot"><button class="btn btn-outline" data-cg-close>Cancel</button><button class="btn btn-primary" data-go data-tour="trade-confirm-button">Trade now →</button></div></div>');
    const hd = CG.modal.open(el, { title: 'Trade Preview', description: 'Review your strategy before trading' });
    el.querySelector('[data-go]').addEventListener('click', () => { hd.close(); if (!ctx.batch && !ctx.strategy && !(AN.name || '').trim()) { T.openSaveDialog('trade', (s) => startTrade(Object.assign({}, ctx, { strategy: s, fromBuilder: true }))); return; } startTrade(ctx); });
    return hd;
  };
  function startTrade(ctx) {
    const live = ctx.mode === 'live'; const status = live ? 'LIVE' : 'PAPER'; const bname = brokerName(ctx.brokerId); const useCustom = ctx.fromBuilder && AN.mode === 'custom';
    const entryOf = (l, asset) => useCustom ? l.price : quoteLeg(l, asset).mark;
    if (ctx.batch) { ctx.batch.forEach((s) => { s.status = 'LIVE'; s.tradingMode = 'LIVE'; s.brokerId = ctx.brokerId; s.liveStartedAt = nowIso(); s.orders = s.legs.map((l, i) => ({ legIdx: i, legId: l.id, status: l.status === 'SQUARED_OFF' ? 'closed' : 'filled', orderId: l.status === 'SQUARED_OFF' ? null : T._h.nextOrderId(), fill: l.entryPremium })); recalc(s); pushHistory(s); }); bumpUsage('live', ctx.batch.length); renderAll(); CG.toast({ title: 'Live Orders Placed', description: ctx.batch.length + (ctx.batch.length === 1 ? ' strategy' : ' strategies') + ' moved to live on ' + bname, variant: 'success' }); CG.emit('analyse:set-tab', 'live'); CG.emit('analyse:strategies-changed'); return; }
    let s = ctx.strategy;
    if (s && ctx.fromBuilder) { if (!(s.status === 'PAPER' || s.status === 'LIVE')) { s.legs = AN.legs.map(toStratLeg); s.asset = AN.asset; } if ((AN.name || '').trim()) s.name = AN.name.trim(); }
    if (!s) s = createStrategy({ name: (AN.name || '').trim() || guessTemplate(AN.legs), asset: AN.asset, legs: AN.legs, status: 'DRAFT' });
    const wasActive = s.status === 'PAPER' || s.status === 'LIVE';
    s.status = status; s.tradingMode = status; s.brokerId = ctx.brokerId;
    if (!wasActive) { s.startedAt = nowIso(); s.closedAt = null; s.legs.forEach((l) => { l.status = 'OPEN'; l.exitPremium = null; l.isAdjustment = !!l.isAdjustment; const p = entryOf(l, s.asset); l.price = p; l.entryPremium = p; l.currentPrice = p; }); s.pnlHistory = []; }
    if (live) s.orders = s.legs.map((l, i) => ({ legIdx: i, legId: l.id, status: l.status === 'SQUARED_OFF' ? 'closed' : 'filled', orderId: l.status === 'SQUARED_OFF' ? null : T._h.nextOrderId(), fill: l.entryPremium })); else delete s.orders;
    recalc(s); pushHistory(s); bumpUsage(ctx.mode, 1);
    if (ctx.source === 'activate') CG.toast({ title: (live ? 'Live' : 'Paper') + ' Trading Started', description: 'Trading ' + s.name + ' on ' + bname, variant: 'success' });
    else if (live) CG.toast({ title: 'Live Orders Placed', description: s.name + ' · ' + plural(openLegs(s).length, 'order') + ' filled on ' + bname, variant: 'success' });
    else CG.toast({ title: 'Paper Trade Started', description: s.name, variant: 'success' });
    if (ctx.fromBuilder || S.editing === s) { AN.legs = []; AN.name = ''; AN.strategyId = null; S.editing = null; S.dirty = false; legsChanged(); }
    renderAll(); CG.emit('analyse:set-tab', live ? 'live' : 'paper'); CG.emit('analyse:strategies-changed', s); CG.emit('cg-tour:paper-started', s);
    return s;
  }
  T.startTrade = startTrade;
