  // ======================================================================
  // PAPER / LIVE PANELS · card redesign, sort, summary strip
  // ======================================================================
  function filterRows(status, q) { q = (q || '').trim().toLowerCase(); return M.strategies.filter((s) => s.status === status).filter((s) => !q || s.name.toLowerCase().includes(q) || s.asset.toLowerCase().includes(q) || (s.templateName || '').toLowerCase().includes(q)); }
  function sortRows(rows, key) { const r = rows.slice(); r.forEach(recalc); if (key === 'date') r.sort((a, b) => new Date(b.startedAt || b.createdAt) - new Date(a.startedAt || a.createdAt)); else if (key === 'name') r.sort((a, b) => a.name.localeCompare(b.name)); else r.sort((a, b) => b.totalPnl - a.totalPnl); return r; }
  function paperRows() { return sortRows(filterRows('PAPER', S.paperSearch), S.paperSort); }
  function liveRows() { return sortRows(filterRows('LIVE', S.liveSearch), S.liveSort); }
  function legChip(l) { return '<span class="trd-ochip' + (l.status === 'SQUARED_OFF' ? '' : ' filled') + '" title="' + esc(legDesc(l)) + (l.status === 'SQUARED_OFF' ? ' · closed' : '') + '">' + l.side.charAt(0) + ' ' + (l.type === 'FUTURE' ? 'FUT' : l.type.charAt(0) + ' ' + Number(l.strike).toLocaleString('en-US')) + ' · ' + l.lots + (l.status === 'SQUARED_OFF' ? ' · closed' : '') + '</span>'; }
  function ordersHtml(s) { return '<div class="trd-orders">' + s.legs.map((l, i) => { const o = orderFor(s, l, i); const st = l.status === 'SQUARED_OFF' ? 'closed' : (o ? o.status : 'filled'); return '<span class="trd-ochip ' + st + '" title="' + (o && o.orderId ? 'Order ' + o.orderId : st) + '">' + l.side.charAt(0) + ' ' + (l.type === 'FUTURE' ? 'FUT' : l.type.charAt(0) + ' ' + Number(l.strike).toLocaleString('en-US')) + ' · ' + st + '</span>'; }).join('') + '</div>'; }
  function stratCard(s, kind, first) {
    recalc(s); const open = openLegs(s); const d = daysOf(s);
    let html = '<div class="trd-card" data-id="' + s.id + '"><div class="trd-card-top"><div style="min-width:0"><div class="trd-card-name">' + esc(s.name) + ' ' + modePill(s) + (kind === 'live' && s.orderBatchId ? '<span class="trd-tag">' + esc(s.orderBatchId) + '</span>' : '') + '</div><div class="trd-card-meta"><span class="trd-tag">' + s.asset + '</span><span><b>' + open.length + '</b>/' + s.legs.length + ' legs</span><span><b>' + d + '</b> days</span>' + (s.templateName ? '<span>' + esc(s.templateName) + '</span>' : '') + (s.startedAt ? '<span>since ' + fmtShort(s.startedAt) + '</span>' : '') + '</div></div><div class="trd-card-pnl"><div class="big ' + pnlClass(s.totalPnl) + '" data-pnl="' + s.id + '"' + (first ? ' data-tour="' + kind + '-pnl"' : '') + '>' + smoney(s.totalPnl) + '</div><div class="sub">unreal <b class="' + pnlClass(s.unrealizedPnl) + '" data-upnl="' + s.id + '">' + smoney(s.unrealizedPnl) + '</b> · real <b class="' + pnlClass(s.realizedPnl) + '" data-rpnl="' + s.id + '">' + smoney(s.realizedPnl) + '</b></div></div></div>';
    html += '<div class="trd-card-mid">' + sparkline(s) + (kind === 'live' ? ordersHtml(s) : '<div class="trd-orders">' + s.legs.map(legChip).join('') + '</div>') + '</div>';
    if (kind === 'live') { const failed = (s.orders || []).filter((o) => o.status === 'failed'); if (failed.length) html += '<div class="alert alert-destructive trd-failed trd-alert"><span>' + I.warn + ' <b>Order placement failed</b> · Retried ' + plural(failed[0].retries || 1, 'time') + (failed.length > 1 ? ' · ' + failed.length + ' legs' : '') + '</span><button class="btn btn-destructive btn-xs" data-act="retry">Retry Failed Orders</button></div>'; }
    html += '<div class="trd-card-actions"><button class="btn btn-outline" data-act="details">Details</button><button class="btn btn-outline" data-act="alert" title="Set a P&L alert for this strategy">' + I.bell + ' Set alert</button>';
    if (kind === 'paper') html += '<button class="btn btn-outline" data-act="golive" title="Place these legs as live orders">' + I.bolt + ' Go live</button><button class="btn btn-outline trd-btn-warn" data-act="stop" data-tour="paper-stop">Stop</button>';
    else html += '<button class="btn btn-outline trd-btn-danger-o" data-act="sqall"' + (open.length ? '' : ' disabled') + '>Square off all</button>';
    html += '<span class="trd-right"><button class="btn btn-ghost text-loss" data-act="delete">Delete</button></span></div></div>';
    return html;
  }
  function stripHtml(kind) {
    const pf = PF.compute(); const st = kind === 'paper' ? 'PAPER' : 'LIVE'; const mine = pf.byStrategy.filter((x) => x.status === st);
    const sum = (k) => mine.reduce((a, x) => a + x[k], 0); const tot = sum('pnl'), day = sum('dayPnl'), delta = sum('delta'), margin = sum('margin'), legs = sum('openLegs');
    const assets = Array.from(new Set(mine.map((x) => x.asset)));
    return '<div class="trd-strip"><div><span class="micro">Total P&amp;L</span><div class="v ' + pnlClass(tot) + '" data-total>' + smoney(tot) + '</div><div class="s">' + plural(mine.length, 'trade') + ' · ' + plural(legs, 'open leg') + '</div></div><div><span class="micro">Day P&amp;L</span><div class="v ' + pnlClass(day) + '" data-day>' + smoney(day) + '</div><div class="s">vs previous close</div></div><div><span class="micro">Net Δ</span><div class="v" data-delta>' + F.signed(delta, 4) + '</div><div class="s">' + (assets.length ? assets.join(' + ') + ' units' : 'no positions') + '</div></div><div><span class="micro">Margin used</span><div class="v" data-margin>' + money(margin) + '</div><div class="s">of ' + money(pf.marginTotal) + ' · ' + (pf.marginTotal ? Math.round(margin / pf.marginTotal * 100) : 0) + '%</div></div></div>';
  }
  function renderList(kind) {
    const el = S.els[kind]; if (!el) return; const rows = kind === 'paper' ? paperRows() : liveRows(); const pageKey = kind + 'Page'; const pages = Math.max(1, Math.ceil(rows.length / PAGE)); if (S[pageKey] > pages) S[pageKey] = pages; const page = rows.slice((S[pageKey] - 1) * PAGE, S[pageKey] * PAGE); const sortKey = S[kind + 'Sort'];
    let html = '<div class="trd-toolbar">' + searchBox('Search ' + kind + ' trades...', S[kind + 'Search'], kind + '-search') + '<select class="select select-sm" data-act="' + kind + '-sort" title="Sort" aria-label="Sort">' + [['pnl', 'Sort · P&L'], ['date', 'Sort · Date'], ['name', 'Sort · Name']].map(([k, l]) => '<option value="' + k + '"' + (sortKey === k ? ' selected' : '') + '>' + l + '</option>').join('') + '</select><button class="btn btn-outline btn-sm btn-icon" data-act="refresh" title="Refresh">' + I.refresh + '</button>' + (kind === 'paper' ? '<button class="btn btn-outline btn-sm" data-act="trade-all" title="Place all paper strategies as live orders">' + I.bolt + ' Trade All → Live</button>' : '<span class="trd-tag" title="Exchange connection">' + (ST.exchangeConnected ? '<i class="trd-live-dot"></i>exchange connected' : 'exchange not connected') + '</span>') + '</div>';
    html += stripHtml(kind) + '<div class="trd-body">';
    if (!rows.length) html += '<div class="empty">' + (S[kind + 'Search'] ? '<b>No matching ' + kind + ' trades</b>Try a different search' : kind === 'paper' ? '<b>No paper trades yet</b>Click Paper trade in the builder to begin' : '<b>No live trades</b>Use Trade All → Live to place real orders on Delta Exchange.') + '</div>';
    else html += '<div class="trd-list">' + page.map((s, i) => stratCard(s, kind, i === 0 && S[pageKey] === 1)).join('') + '</div>' + pager(S[pageKey], rows.length, kind);
    el.innerHTML = html + '</div>';
  }
  function renderPaper() { renderList('paper'); }
  function renderLive() { renderList('live'); }
  function bindList(kind) {
    const el = S.els[kind]; const rerender = kind === 'paper' ? renderPaper : renderLive;
    CG.delegate(el, 'click', '[data-act]', (e, t) => {
      const act = t.dataset.act; const card = t.closest('[data-id]'); const s = card ? byId(card.dataset.id) : null;
      if (act === 'refresh') { M.strategies.forEach(recalc); rerender(); CG.toast({ title: 'Refreshed', description: 'Strategy data has been updated' }); }
      else if (act === 'trade-all') { const all = M.strategies.filter((s) => s.status === 'PAPER' && openLegs(s).length); if (!all.length) return CG.toast({ title: 'No legs', description: 'Add at least one leg to trade', variant: 'destructive' }); T.openTradeMode({ batch: all, mode: 'live' }); }
      else if (act === kind + '-search-clear') { S[kind + 'Search'] = ''; rerender(); }
      else if (act === kind + '-prev') { S[kind + 'Page'] = Math.max(1, S[kind + 'Page'] - 1); rerender(); }
      else if (act === kind + '-next') { S[kind + 'Page'] += 1; rerender(); }
      else if (act === 'details' && s) T.openDetails(s.id);
      else if (act === 'alert' && s) T.openAlert(s.id);
      else if (act === 'golive' && s) T.openTradeMode({ strategy: s, mode: 'live', source: 'golive' });
      else if (act === 'stop' && s) T.openStopDialog(s.id);
      else if (act === 'retry' && s) T.retryFailedOrders(s.id, t);
      else if (act === 'sqall' && s) T.squareOffAll(s.id, t);
      else if (act === 'delete' && s) T.deleteStrategy(s.id, { short: kind === 'live' });
    });
    el.addEventListener('input', (e) => { const t = e.target; if (t.dataset.act === kind + '-search') { S[kind + 'Search'] = t.value; S[kind + 'Page'] = 1; const pos = t.selectionStart; rerender(); const n = el.querySelector('[data-act="' + kind + '-search"]'); if (n) { n.focus(); n.setSelectionRange(pos, pos); } } });
    el.addEventListener('change', (e) => { const t = e.target; if (t.dataset.act === kind + '-sort') { S[kind + 'Sort'] = t.value; S[kind + 'Page'] = 1; rerender(); } });
  }
  function bindPaper() { bindList('paper'); }
  function bindLive() { bindList('live'); }
  T.retryFailedOrders = function (id, btn) { const s = byId(id); if (!s || !s.orders) return; const failed = s.orders.filter((o) => o.status === 'failed'); if (!failed.length) return CG.toast({ title: 'No failed orders', description: 'All legs are already filled' }); if (btn) { btn.disabled = true; btn.textContent = 'Retrying...'; } setTimeout(() => { failed.forEach((o) => { o.status = 'filled'; o.orderId = T._h.nextOrderId(); o.retries = (o.retries || 0) + 1; const leg = s.legs.find((l) => l.id === o.legId) || s.legs[o.legIdx]; if (leg) o.fill = leg.entryPremium; }); renderLive(); if (S.details && S.details.id === id) S.details.render(); portfolioChanged(); CG.toast({ title: 'Orders placed', description: 'Failed legs were submitted successfully.', variant: 'success' }); }, 1000); };
  T.squareOffAll = async function (id, btn) {
    const s = byId(id); if (!s) return; const open = openLegs(s); if (!open.length) return CG.toast({ title: 'Nothing to square off', description: 'No active legs' });
    const live = s.status === 'LIVE';
    const ok = await CG.modal.confirm({ title: 'Square Off All Positions', description: live ? 'Market orders will be placed on Delta Exchange to close all positions with full quantity.' : 'All ' + plural(open.length, 'active leg') + ' will be squared off at current market prices. This cannot be undone.', confirmText: live ? 'Square Off All' : 'Square Off', variant: 'destructive' });
    if (!ok) return; if (btn) { btn.disabled = true; btn.textContent = 'Exiting...'; }
    const finish = () => { open.forEach((l) => { l.exitPremium = currentPrice(l, s.asset); l.status = 'SQUARED_OFF'; l.closedAt = nowIso(); }); if (s.orders) s.orders.forEach((o) => { if (o.status !== 'closed') o.status = 'closed'; }); if (live) { s.status = 'ARCHIVED'; s.closedAt = nowIso(); } recalc(s); pushHistory(s); if (S.editing === s) T.loadStrategy(s, { silent: true }); renderAll(); if (S.details && S.details.id === id) S.details.render(); CG.emit('analyse:strategies-changed', s); CG.toast({ title: live ? 'Positions closed' : 'Squared off', description: live ? 'All legs squared off at market · strategy archived' : plural(open.length, 'leg') + ' squared off at current prices', variant: 'success' }); };
    if (live) setTimeout(finish, 800); else finish();
  };
  // ======================================================================
  // STRATEGY DETAILS (modal, size lg) · tiles, mini payoff, legs, history, stats, alert
  // ======================================================================
  function pnlChart(s) { const hist = (s.pnlHistory || []); const pts = hist.map((p) => p.pnl); pts.push(s.totalPnl); if (pts.length < 2) pts.unshift(0); const W = 600, H = 110, pad = 8, mL = 40; const min = Math.min(0, ...pts), max = Math.max(0, ...pts); const rng = (max - min) || 1; const x = (i) => (mL + (W - mL - pad) * i / (pts.length - 1)).toFixed(1); const y = (v) => (pad + (H - 2 * pad - 10) * (1 - (v - min) / rng)).toFixed(1); const d = pts.map((v, i) => (i ? 'L' : 'M') + x(i) + ' ' + y(v)).join(' '); const z = y(0); const last = pts[pts.length - 1]; const c = last >= 0 ? 'hsl(var(--profit))' : 'hsl(var(--loss))'; let g = ''; [min, max].forEach((v) => { if (Math.abs(v) < 1e-9) return; g += '<line x1="' + mL + '" x2="' + (W - pad) + '" y1="' + y(v) + '" y2="' + y(v) + '" stroke="hsl(var(--border))"/><text x="' + (mL - 6) + '" y="' + (+y(v) + 3) + '" text-anchor="end">' + smoney(v, 0) + '</text>'; }); return '<svg viewBox="0 0 ' + W + ' ' + H + '" class="trd-hist trd-payoff-mini" aria-label="P&L history">' + g + '<line x1="' + mL + '" x2="' + (W - pad) + '" y1="' + z + '" y2="' + z + '" stroke="hsl(var(--muted-foreground))" stroke-dasharray="2 3"/><path d="' + d + ' L' + x(pts.length - 1) + ' ' + z + ' L' + x(0) + ' ' + z + ' Z" fill="' + c + '" opacity=".12"/><path d="' + d + '" fill="none" stroke="' + c + '" stroke-width="1.6" stroke-linejoin="round"/><circle cx="' + x(pts.length - 1) + '" cy="' + y(last) + '" r="3.5" fill="' + c + '"/><text x="' + (+x(pts.length - 1) - 6) + '" y="' + (+y(last) - 7) + '" text-anchor="end" fill="' + c + '" font-weight="500">' + smoney(last) + '</text>' + (hist.length ? '<text x="' + mL + '" y="' + (H - 2) + '">' + fmtShort(hist[0].date) + '</text><text x="' + (W - pad) + '" y="' + (H - 2) + '" text-anchor="end">today</text>' : '') + '</svg>'; }
  function legRow(s, l, i) {
    const p = legPnl(l, s.asset); const closed = l.status === 'SQUARED_OFF'; const o = orderFor(s, l, i); const activeS = s.status === 'PAPER' || s.status === 'LIVE';
    return '<div class="trd-legrow ' + (l.side === 'SELL' ? 'sell' : 'buy') + (closed ? ' closed' : '') + '" data-leg="' + l.id + '">' + sideBadge(l.side) + insCell(l, s.asset) + '<span class="r qty">' + l.lots + ' lots</span><span class="px">entry <b>' + F.num(p.entry, 1) + '</b> → ' + (closed ? 'exit <b>' + F.num(p.current, 1) + '</b>' : 'now <b class="now" data-lnow="' + l.id + '">' + F.num(p.current, 1) + '</b>') + (o && o.status === 'failed' ? ' <span class="trd-ochip failed">order failed</span>' : o && o.status === 'pending' ? ' <span class="trd-ochip pending">pending</span>' : '') + '</span><span class="r"><span class="trd-pill ' + (p.pnl >= 0 ? 'up' : 'down') + '" data-lpnl="' + l.id + '">' + smoney(p.pnl) + '</span></span><span class="r">' + (!closed && activeS ? '<button class="btn btn-outline btn-xs trd-btn-danger-o" data-act="sqoff" data-leg="' + l.id + '">Square off</button>' : '') + '</span></div>';
  }
  T.openDetails = function (id) {
    const s = byId(id); if (!s) return null; let tab = 'active';
    const el = h('<div class="trd-dlg trd-details' + (S.density === 'compact' ? ' trd-compact' : '') + '"></div>');
    const off = CG.on('tick', () => tickDetails());
    const hd = CG.modal.open(el, { size: 'lg', noClose: true, onClose: () => { off(); if (S.details && S.details.id === id) S.details = null; } });
    function render() {
      recalc(s); const live = s.status === 'LIVE', paper = s.status === 'PAPER', activeS = live || paper; const open = openLegs(s), sq = s.legs.filter((l) => l.status === 'SQUARED_OFF'); const shown = tab === 'active' ? open : sq; const adj = shown.filter((l) => l.isAdjustment), orig = shown.filter((l) => !l.isAdjustment);
      const payLegs = open.length ? open : s.legs; let r = null; try { if (payLegs.length) r = CG.analyze(payLegs.map(entryPriced), s.asset); } catch (e) { }
      let html = '<div class="trd-dt-head"><div style="min-width:0"><span class="micro">Strategy details</span><h3>' + esc(s.name) + '</h3><div class="trd-dt-sub">' + modePill(s) + '<span class="trd-tag">' + esc(s.asset) + '</span>' + (s.templateName ? '<span class="text-muted">' + esc(s.templateName) + '</span>' : '') + '<span class="micro">' + esc(s.id) + '</span>' + (s.brokerId ? '<span class="micro">· ' + esc(brokerName(s.brokerId)) + '</span>' : '') + (s.orderBatchId ? '<span class="micro">· ' + esc(s.orderBatchId) + '</span>' : '') + '</div></div><button class="cg-dialog-close" aria-label="Close" data-cg-close>✕</button></div><div class="trd-dt-body">';
      html += '<div class="trd-tiles"><div class="trd-tile big"><span class="micro">Total P&amp;L</span><b class="' + pnlClass(s.totalPnl) + '" data-dtot>' + smoney(s.totalPnl) + '</b><span class="s">' + (activeS ? 'live · mark basis' : 'final') + '</span></div><div class="trd-tile"><span class="micro">Unrealised</span><b class="' + pnlClass(s.unrealizedPnl) + '" data-dun>' + smoney(s.unrealizedPnl) + '</b></div><div class="trd-tile"><span class="micro">Realised</span><b class="' + pnlClass(s.realizedPnl) + '" data-dre>' + smoney(s.realizedPnl) + '</b></div><div class="trd-tile"><span class="micro">Days</span><b>' + daysOf(s) + '</b><span class="s">' + (s.startedAt ? 'since ' + fmtShort(s.startedAt) : 'not started') + '</span></div><div class="trd-tile"><span class="micro">Legs</span><b>' + open.length + '<span class="text-muted">/' + s.legs.length + '</span></b><span class="s">' + plural(sq.length, 'closed') + '</span></div><div class="trd-tile"><span class="micro">Margin est.</span><b>' + (r ? money(r.margin) : '—') + '</b><span class="s">' + (r && r.pop != null ? 'POP ' + Math.round(r.pop * 100) + '%' : '') + '</span></div></div>';
      html += '<div class="trd-dt-actions">';
      if (activeS) html += '<button class="btn btn-outline btn-sm" data-act="alert">' + I.bell + ' Set alert</button><button class="btn btn-outline btn-sm" data-act="adjust" title="' + (open.length >= 10 ? 'Maximum 10 active legs reached' : 'Add adjustment legs from the options chain') + '"' + (open.length >= 10 ? ' disabled' : '') + '>' + I.plus + ' Add adjustment</button><button class="btn btn-outline btn-sm" data-act="partial"' + (open.length ? '' : ' disabled') + '>Partial exit</button><button class="btn btn-outline btn-sm trd-btn-danger-o" data-act="sqall"' + (open.length ? '' : ' disabled') + '>Square off all</button>' + (paper ? '<button class="btn btn-outline btn-sm trd-btn-warn" data-act="stop">Stop</button>' : '') + '<button class="btn btn-ghost btn-sm" data-act="refresh" style="margin-left:auto">' + I.refresh + ' Refresh</button>';
      else html += '<span class="trd-tag">' + (s.status === 'ARCHIVED' ? 'archived' : 'draft') + (s.tradingMode ? ' · was ' + (s.tradingMode === 'LIVE' ? 'live' : 'paper') : '') + '</span><button class="btn btn-outline btn-sm" data-act="load">Load in builder</button>' + (s.status === 'DRAFT' ? '<button class="btn btn-primary btn-sm" data-act="activate">Activate</button>' : '') + (s.status === 'ARCHIVED' ? '<button class="btn btn-ghost btn-sm" data-act="journal" style="margin-left:auto">' + I.book + ' Open in Journal</button>' : '');
      html += '</div>';
      if (r) html += '<div class="trd-sec"><span class="micro">Payoff · at expiry</span><span class="trd-mini-kv"><span>Max profit <b class="text-profit">' + (isFinite(r.maxProfit) ? smoney(r.maxProfit) : '∞') + '</b></span><span>Max loss <b class="text-loss">' + (isFinite(r.maxLoss) ? smoney(r.maxLoss) : '−∞') + '</b></span><span>BE <b>' + (r.breakevens.length ? r.breakevens.map(fmtK).join(' / ') : '—') + '</b></span><span>Net Δ <b>' + F.signed(r.greeks.delta, 4) + '</b></span><span>Θ/day <b class="' + pnlClass(r.greeks.theta) + '">' + smoney(r.greeks.theta) + '</b></span></span></div>' + payoffSvg(r, { w: 600, h: 150, pad: 8, cls: 'trd-payoff-mini', par: 'xMidYMid meet', grid: true, spot: true, labels: true, sw: 1.5 });
      html += '<div class="trd-sec"><div class="trd-legtabs"><button class="' + (tab === 'active' ? 'active' : '') + '" data-act="tab" data-tab="active">Active <span class="cnt">' + open.length + '</span></button><button class="' + (tab === 'closed' ? 'active' : '') + '" data-act="tab" data-tab="closed">Squared off <span class="cnt">' + sq.length + '</span></button></div><span class="trd-right micro">' + (live ? 'orders on ' + esc(brokerName(s.brokerId)) : paper ? 'simulated at live prices' : '') + '</span></div>';
      if (!shown.length) html += '<div class="empty">' + (tab === 'active' ? '<b>No active legs</b>All legs have been squared off' : '<b>No squared off legs</b>Closed legs will appear here') + '</div>';
      if (adj.length) html += '<div class="trd-grp">Adjustments</div><div class="trd-legrows">' + adj.map((l) => legRow(s, l, s.legs.indexOf(l))).join('') + '</div>';
      if (orig.length) html += '<div class="trd-grp">' + (adj.length ? 'Original legs' : 'Legs') + '</div><div class="trd-legrows">' + orig.map((l) => legRow(s, l, s.legs.indexOf(l))).join('') + '</div>';
      html += '<div class="trd-sec"><span class="micro">P&amp;L history</span><span class="micro">' + plural((s.pnlHistory || []).length + 1, 'point') + '</span></div>' + pnlChart(s);
      html += '<div class="trd-sec"><span class="micro">Trading statistics</span></div><div class="trd-stats"><div><span class="micro">Open positions</span><b>' + open.length + '</b></div><div><span class="micro">Closed positions</span><b>' + sq.length + '</b></div><div><span class="micro">Total legs</span><b>' + s.legs.length + '</b></div><div><span class="micro">Days</span><b>' + daysOf(s) + '</b></div><div><span class="micro">Realised</span><b class="' + pnlClass(s.realizedPnl) + '">' + smoney(s.realizedPnl) + '</b></div><div><span class="micro">Unrealised</span><b class="' + pnlClass(s.unrealizedPnl) + '">' + smoney(s.unrealizedPnl) + '</b></div><div><span class="micro">Started</span><b>' + (s.startedAt ? fmtDate(s.startedAt) : '—') + '</b></div><div><span class="micro">' + (s.closedAt ? 'Closed' : 'Created') + '</span><b>' + fmtDate(s.closedAt || s.createdAt) + '</b></div></div>';
      if (s.status === 'ARCHIVED' && ((s.tags && s.tags.length) || s.notes)) html += '<div class="trd-sec"><span class="micro">Journal</span></div><div class="trd-box"><div class="trd-tags">' + (s.tags || []).map((t) => '<span class="trd-tagc on">' + esc(t) + '</span>').join('') + '</div>' + (s.notes ? '<p class="text-sm mt-2">' + esc(s.notes) + '</p>' : '') + '</div>';
      html += '</div><div class="trd-dt-foot"><button class="btn btn-outline" data-cg-close>Close</button></div>';
      el.innerHTML = html;
    }
    function tickDetails() { if (!(s.status === 'PAPER' || s.status === 'LIVE')) return; recalc(s); s.legs.forEach((l) => { if (l.status === 'SQUARED_OFF') return; const p = legPnl(l, s.asset); const n = el.querySelector('[data-lnow="' + l.id + '"]'); if (n) n.textContent = F.num(p.current, 1); const pill = el.querySelector('[data-lpnl="' + l.id + '"]'); if (pill) { pill.className = 'trd-pill ' + (p.pnl >= 0 ? 'up' : 'down'); pill.textContent = smoney(p.pnl); } }); const set = (sel, v) => { const n = el.querySelector(sel); if (n) { n.textContent = smoney(v); n.className = pnlClass(v); } }; set('[data-dtot]', s.totalPnl); set('[data-dun]', s.unrealizedPnl); set('[data-dre]', s.realizedPnl); }
    S.details = { id, render, close: () => hd.close() };
    CG.delegate(el, 'click', '[data-act]', (e, t) => {
      const act = t.dataset.act;
      if (act === 'tab') { tab = t.dataset.tab; render(); }
      else if (act === 'refresh') { recalc(s); render(); CG.toast({ title: 'Refreshed', description: 'Strategy data has been updated' }); }
      else if (act === 'alert') T.openAlert(s.id);
      else if (act === 'stop') T.openStopDialog(s.id, { onDone: () => { if (s.status === 'PAPER' || s.status === 'LIVE') render(); else hd.close(); } });
      else if (act === 'sqall') T.squareOffAll(s.id, t);
      else if (act === 'partial') T.openPartialExit(s.id, { onDone: render });
      else if (act === 'sqoff') T.openSquareOff(s.id, t.dataset.leg, { onDone: render });
      else if (act === 'adjust') T.openAdjustment(s.id, { onDone: render });
      else if (act === 'load') { hd.close(); T.loadStrategy(s.id); }
      else if (act === 'activate') { hd.close(); T.openTradeMode({ strategy: s, source: 'activate' }); }
      else if (act === 'journal') { hd.close(); CG.emit('analyse:set-tab', 'journal'); }
    });
    render();
    return hd;
  };
  // ---------- add adjustment (chain modal → [confirm order if live] → append legs) ----------
  T.openAdjustment = function (id, opts) {
    opts = opts || {}; const s = byId(id); if (!s) return; const active = openLegs(s).length; if (active >= 10) return CG.toast({ title: 'Limit Reached', description: 'Maximum 10 active legs allowed per strategy', variant: 'destructive' });
    const exp = (s.legs.find((l) => l.type !== 'FUTURE') || {}).expiry;
    const place = (legs, chainHd) => { legs.forEach((l) => { const leg = normLeg(l, s.asset); leg.isAdjustment = true; leg.entryPremium = leg.price; s.legs.push(leg); if (s.orders) s.orders.push({ legIdx: s.legs.length - 1, legId: leg.id, status: 'filled', orderId: T._h.nextOrderId(), fill: leg.price }); }); recalc(s); pushHistory(s); if (chainHd) chainHd.close(); CG.toast({ title: 'Adjustment added', description: legs.length + ' adjustment leg' + (legs.length > 1 ? 's' : '') + ' added successfully', variant: 'success' }); T.loadStrategy(s, { silent: true }); renderAll(); if (opts.onDone) opts.onDone(); CG.emit('analyse:strategies-changed', s); };
    T.openChainModal({ asset: s.asset, expiry: exp, max: 10 - active, title: 'Select Option from Chain', onAdd: (legs, chainHd) => { if (s.status === 'LIVE') T.openAdjustmentConfirm(s.id, legs, () => place(legs, chainHd)); else place(legs, chainHd); } });
  };
  T.openAdjustmentConfirm = function (id, legs, onPlaced) {
    const s = byId(id); if (!s) return; const priced = legs.map((l) => normLeg(l, s.asset)); let r = null; try { r = CG.analyze(priced, s.asset); } catch (e) { } const np = r ? r.netPremium : 0; const f = feeFor(priced, s.asset, brokerOf(s.brokerId)); const lot = lotOf(s.asset);
    const el = h('<div class="trd-dlg"><div class="cg-dialog-head"><div><div class="cg-dialog-title flex items-center gap-2">Confirm Adjustment Order ' + modePill('LIVE') + '</div><div class="cg-dialog-desc">' + esc(s.name) + ' · ' + esc(brokerName(s.brokerId)) + '</div></div><button class="cg-dialog-close" aria-label="Close" data-cg-close>✕</button></div><div class="cg-dialog-body"><table class="trd-pv"><thead><tr><th class="l">Side</th><th class="l">Instrument</th><th>Lots</th><th>Est. price</th><th>Value</th></tr></thead><tbody>' + priced.map((l) => '<tr><td class="l">' + sideBadge(l.side) + '</td><td class="l">' + insCell(l, s.asset) + '</td><td>' + l.lots + '</td><td>' + F.num(l.price, 1) + '</td><td>' + money(l.price * l.lots * lot) + '</td></tr>').join('') + '</tbody></table><div class="trd-kv mt-3"><span>Net premium</span><b class="' + (np >= 0 ? 'text-profit' : '') + '">' + (np >= 0 ? 'Credit ' : 'Debit ') + money(Math.abs(np)) + '</b><span>Fees · est.</span><b>' + money(f.total) + '</b><span class="trd-kv-sum">' + (np - f.total >= 0 ? 'You will receive' : 'You will pay') + '</span><b class="trd-kv-sum">' + money(Math.abs(np - f.total)) + '</b><span>Expected required margin</span><b>' + (r ? money(r.margin) : '—') + '</b></div>' + noteBox('destructive', '', 'These order(s) will be placed on the exchange with real funds at market. Fill prices may differ from the estimate above.') + '</div><div class="cg-dialog-foot"><button class="btn btn-outline" data-cg-close>Cancel</button><button class="btn btn-primary" data-go>Place order</button></div></div>');
    const hd = CG.modal.open(el, { noClose: true });
    el.querySelector('[data-go]').addEventListener('click', (e) => { const b = e.currentTarget; b.disabled = true; b.textContent = 'Placing...'; setTimeout(() => { hd.close(); onPlaced(); }, 800); });
    return hd;
  };
  // ======================================================================
  // SQUARE OFF (single leg, optional partial qty)
  // ======================================================================
  function squareOffLeg(s, leg, exit, qty) { qty = Math.max(1, Math.min(Math.round(qty || leg.lots), leg.lots)); const idx = s.legs.indexOf(leg); if (qty < leg.lots) { const closed = Object.assign(cloneLeg(leg), { id: CG.newLegId(), lots: qty, status: 'SQUARED_OFF', exitPremium: exit, closedAt: nowIso() }); leg.lots -= qty; s.legs.splice(idx + 1, 0, closed); if (s.orders) s.orders.push({ legIdx: idx + 1, legId: closed.id, status: 'closed', orderId: null, fill: exit }); } else { leg.status = 'SQUARED_OFF'; leg.exitPremium = exit; leg.closedAt = nowIso(); const o = orderFor(s, leg, idx); if (o) o.status = 'closed'; } recalc(s); pushHistory(s); if (S.editing === s) T.loadStrategy(s, { silent: true }); renderAll(); CG.emit('analyse:strategies-changed', s); }
  T.openSquareOff = function (sid, legId, opts) {
    opts = opts || {}; const s = byId(sid); const leg = s && s.legs.find((l) => l.id === legId); if (!leg || leg.status === 'SQUARED_OFF') return null;
    const live = s.status === 'LIVE'; const cur = currentPrice(leg, s.asset); const entry = leg.entryPremium != null ? leg.entryPremium : leg.price; const lot = lotOf(s.asset);
    const el = h('<div class="trd-dlg"><div class="cg-dialog-body"><div class="trd-box"><div class="trd-box-title">Position</div><div class="trd-pos-grid"><div><small>Leg</small><b style="font-family:var(--font-body)">' + sideBadge(leg.side) + ' ' + typeBadge(leg.type) + (leg.isAdjustment ? ' <span class="trd-tag">adj</span>' : '') + '</b></div><div><small>' + (leg.type === 'FUTURE' ? 'Symbol' : 'Strike') + '</small><b>' + (leg.type === 'FUTURE' ? esc(leg.symbol) : Number(leg.strike).toLocaleString('en-US')) + '</b></div><div><small>Quantity</small><b>' + leg.lots + ' <span class="text-xs text-muted">lots × ' + lot + '</span></b></div><div><small>Entry premium</small><b>' + F.num(entry, 1) + '</b></div></div></div>' +
      '<div class="grid grid-2 gap-3"><div class="field"><label class="label">Exit premium</label><input type="number" step="0.1" min="0" class="input mono" data-exit placeholder="' + (live ? 'Leave empty for market' : 'Enter exit premium') + '" value="' + cur.toFixed(1) + '"><div class="hint">Market ' + F.num(cur, 1) + ' · or your desired exit price</div></div><div class="field"><label class="label">Exit qty (max ' + leg.lots + ')</label><input type="number" min="1" max="' + leg.lots + '" step="1" class="input mono" data-qty value="' + leg.lots + '"><div class="hint">Less than ' + leg.lots + ' = partial exit</div></div></div>' +
      '<div class="trd-box"><div class="trd-box-title">Realised P&amp;L</div><div class="trd-kv"><span>Entry value</span><b data-ev></b><span>Exit value</span><b data-xv></b><span class="trd-kv-sum">Net P&amp;L</span><b class="trd-kv-sum" data-np></b></div></div>' +
      noteBox('warning', '', 'This action cannot be undone. The position will be closed and P&L will be realised.') + '</div><div class="cg-dialog-foot"><button class="btn btn-outline" data-cg-close>Cancel</button><button class="btn btn-destructive" data-go>Confirm square off</button></div></div>');
    const hd = CG.modal.open(el, { title: 'Square Off Position', description: 'Close this ' + (leg.type === 'FUTURE' ? 'futures' : 'option') + ' leg' });
    const exitIn = el.querySelector('[data-exit]'), qtyIn = el.querySelector('[data-qty]');
    const calc = () => { const ex = exitIn.value === '' ? cur : Math.max(0, +exitIn.value || 0); const q = Math.max(1, Math.min(Math.round(+qtyIn.value || 1), leg.lots)); const sign = leg.side === 'BUY' ? 1 : -1; const ev = entry * q * lot, xv = ex * q * lot, np = (ex - entry) * q * lot * sign; el.querySelector('[data-ev]').textContent = money(ev); el.querySelector('[data-xv]').textContent = money(xv); const n = el.querySelector('[data-np]'); n.textContent = smoney(np); n.className = 'trd-kv-sum ' + pnlClass(np); return { ex, q }; };
    el.addEventListener('input', calc); calc();
    el.querySelector('[data-go]').addEventListener('click', (e) => { const { ex, q } = calc(); const b = e.currentTarget; b.disabled = true; b.textContent = 'Closing...'; setTimeout(() => { squareOffLeg(s, leg, ex, q); hd.close(); CG.toast({ title: 'Leg squared off successfully', description: 'Leg squared off at ' + F.num(ex, 1), variant: 'success' }); if (opts.onDone) opts.onDone(); }, 600); });
    return hd;
  };
  // ======================================================================
  // PARTIAL EXIT
  // ======================================================================
  T.openPartialExit = function (sid, opts) {
    opts = opts || {}; const s = byId(sid); if (!s) return null; const open = openLegs(s); if (!open.length) return CG.toast({ title: 'No active legs', description: 'Nothing to exit' });
    const sel = new Set(); let pct = 50;
    const el = h('<div class="trd-dlg"></div>');
    const hd = CG.modal.open(el, { title: 'Partial Exit', description: 'Select legs and choose exit percentage' });
    function render() {
      el.innerHTML = '<div class="cg-dialog-body"><div class="flex items-center justify-between mb-2"><span class="micro" data-count>' + plural(open.length, 'active leg') + ' · ' + sel.size + ' selected</span><div class="flex gap-1"><button class="btn btn-ghost btn-xs" data-act="all">Select all</button><button class="btn btn-ghost btn-xs" data-act="none">Deselect all</button></div></div>' +
        open.map((l) => { const cur = currentPrice(l, s.asset); return '<label class="trd-pe-row"><input type="checkbox" class="checkbox" data-leg="' + l.id + '"' + (sel.has(l.id) ? ' checked' : '') + '>' + sideBadge(l.side) + insCell(l, s.asset) + '<span class="text-muted mono">' + l.lots + ' → <b data-exq="' + l.id + '">' + Math.max(1, Math.round(l.lots * pct / 100)) + '</b> lots</span><span class="ml-auto micro">Exit</span><input type="number" step="0.1" min="0" class="input mono" data-px="' + l.id + '" value="' + cur.toFixed(1) + '" title="Exit price (default: current market)"></label>'; }).join('') +
        '<div class="field mt-3"><label class="label">Exit %</label><div class="trd-pct-chips">' + [25, 50, 75, 100].map((p) => '<button class="trd-chip' + (pct === p ? ' active' : '') + '" data-act="pct" data-pct="' + p + '">' + p + '%</button>').join('') + '<button class="trd-chip' + (![25, 50, 75, 100].includes(pct) ? ' active' : '') + '" data-act="custom">Custom</button><input type="number" min="1" max="100" class="input mono" data-custom value="' + pct + '" aria-label="Custom exit percent">%</div><div class="hint">Exit quantity per leg = round(qty × ' + pct + '%) · minimum 1 lot</div></div></div><div class="cg-dialog-foot"><button class="btn btn-outline" data-cg-close>Cancel</button><button class="btn btn-destructive" data-go' + (sel.size ? '' : ' disabled') + '>Exit ' + plural(sel.size, 'leg') + '</button></div>';
    }
    CG.delegate(el, 'click', '[data-act],[data-go]', (e, t) => {
      const act = t.dataset.act;
      if (act === 'all') { open.forEach((l) => sel.add(l.id)); render(); }
      else if (act === 'none') { sel.clear(); render(); }
      else if (act === 'pct') { pct = +t.dataset.pct; render(); }
      else if (act === 'custom') { el.querySelector('[data-custom]').focus(); }
      else if (t.hasAttribute('data-go')) { if (!sel.size) return; const b = t; b.disabled = true; b.textContent = 'Exiting...'; const prices = {}; CG.$$('[data-px]', el).forEach((i) => { prices[i.dataset.px] = i.value === '' ? null : +i.value; }); setTimeout(() => { let n = 0; open.filter((l) => sel.has(l.id)).forEach((l) => { const q = Math.max(1, Math.round(l.lots * pct / 100)); const ex = prices[l.id] != null ? prices[l.id] : currentPrice(l, s.asset); squareOffLeg(s, l, ex, q); n++; }); hd.close(); CG.toast({ title: 'Partial exit complete', description: plural(n, 'leg') + ' exited at ' + pct + '%', variant: 'success' }); if (opts.onDone) opts.onDone(); }, 600); }
    });
    el.addEventListener('change', (e) => { const t = e.target; if (t.dataset.leg) { if (t.checked) sel.add(t.dataset.leg); else sel.delete(t.dataset.leg); const b = el.querySelector('[data-go]'); b.disabled = !sel.size; b.textContent = 'Exit ' + plural(sel.size, 'leg'); el.querySelector('[data-count]').textContent = plural(open.length, 'active leg') + ' · ' + sel.size + ' selected'; } if (t.hasAttribute('data-custom')) { pct = Math.max(1, Math.min(100, Math.round(+t.value || 1))); render(); } });
    render();
    return hd;
  };
  // ======================================================================
  // STOP PAPER TRADING
  // ======================================================================
  T.openStopDialog = function (sid, opts) {
    opts = opts || {}; const s = byId(sid); if (!s) return null; let archive = true; const open = openLegs(s); const liveOk = ST.liveFeed !== false;
    const el = h('<div class="trd-dlg"></div>');
    const off = CG.on('tick', () => { recalc(s); open.forEach((l) => { const n = el.querySelector('[data-lp="' + l.id + '"]'); if (n) n.textContent = F.num(currentPrice(l, s.asset), 1); }); const p = el.querySelector('[data-pnl]'); if (p) { p.textContent = smoney(s.totalPnl); p.className = 'mono ' + pnlClass(s.totalPnl); } });
    const hd = CG.modal.open(el, { title: 'Stop Paper Trading', description: 'Choose what to do with this strategy', onClose: off });
    function render() {
      recalc(s);
      el.innerHTML = '<div class="cg-dialog-body"><div class="trd-box"><div class="flex items-center gap-2 flex-wrap"><b>' + esc(s.name) + '</b>' + modePill(s) + '<span class="trd-tag"><i class="trd-live-dot"></i>live prices</span></div><div class="flex gap-4 mt-2 text-xs text-muted flex-wrap mono"><span>Asset <b>' + esc(s.asset) + '</b></span><span>Legs <b>' + s.legs.length + '</b></span><span>P&amp;L <b class="mono ' + pnlClass(s.totalPnl) + '" data-pnl>' + smoney(s.totalPnl) + '</b></span></div></div>' +
        (open.length ? '<div class="trd-box-title">Active legs</div><div class="trd-leglist">' + open.map((l) => '<div class="trd-legline">' + sideBadge(l.side) + insCell(l, s.asset) + '<span class="text-muted mono">' + l.lots + ' lots</span><span class="mono" data-lp="' + l.id + '">' + F.num(currentPrice(l, s.asset), 1) + '</span></div>').join('') + '</div>' : '<div class="empty" style="padding:14px"><b>No active legs</b>All legs are already squared off</div>') +
        (liveOk ? '<div class="trd-note ok"><span class="text-profit">' + I.check + '</span><div><b>Using live WebSocket prices</b><div class="text-xs text-muted">Current market prices will be used for all legs when stopping</div></div></div>' : '<div class="trd-note wait"><span class="spinner"></span><div><b>Connecting to live prices</b><div class="text-xs text-muted">Please wait while we fetch current market prices...</div></div></div>') +
        '<label class="trd-check"><input type="checkbox" class="checkbox" data-arch' + (archive ? ' checked' : '') + (liveOk ? '' : ' disabled') + ' style="margin-top:2px"><div><b>Archive this strategy</b><span>Move to archived strategies and the Journal. Uncheck to keep it as a draft for future use.</span></div></label><div class="hint mt-2" data-hint>' + (archive ? 'Strategy will be moved to Archived Strategies and marked as closed. All active legs will be squared off at current prices.' : 'Strategy will remain in Draft Strategies but paper trading will be stopped. Legs stay saved so you can activate it again later.') + '</div></div>' +
        '<div class="cg-dialog-foot"><button class="btn btn-outline" data-cg-close>Cancel</button><button class="btn btn-outline trd-btn-warn" data-go' + (liveOk ? '' : ' disabled') + ' title="' + (liveOk ? 'Stop paper trading' : 'Waiting for live prices...') + '">' + (liveOk ? 'Stop trading' : 'Connecting...') + '</button></div>';
    }
    el.addEventListener('change', (e) => { if (e.target.hasAttribute('data-arch')) { archive = e.target.checked; el.querySelector('[data-hint]').textContent = archive ? 'Strategy will be moved to Archived Strategies and marked as closed. All active legs will be squared off at current prices.' : 'Strategy will remain in Draft Strategies but paper trading will be stopped. Legs stay saved so you can activate it again later.'; } });
    el.addEventListener('click', (e) => { const b = e.target.closest('[data-go]'); if (!b) return; b.disabled = true; b.textContent = 'Stopping...'; setTimeout(() => { if (archive) { open.forEach((l) => { l.exitPremium = currentPrice(l, s.asset); l.status = 'SQUARED_OFF'; l.closedAt = nowIso(); }); s.status = 'ARCHIVED'; s.closedAt = nowIso(); } else { s.status = 'DRAFT'; s.tradingMode = null; s.startedAt = null; s.legs.forEach((l) => { if (l.status !== 'SQUARED_OFF') { l.price = l.entryPremium != null ? l.entryPremium : l.price; } }); } recalc(s); pushHistory(s); if (S.editing === s) { S.editing = null; AN.strategyId = null; renderBuilder(); } renderAll(); hd.close(); CG.emit('analyse:strategies-changed', s); CG.toast({ title: 'Paper trading stopped', description: archive ? s.name + ' archived · legs squared off at live prices' : s.name + ' moved to Draft Strategies', variant: 'success' }); if (opts.onDone) opts.onDone(); }, 700); });
    render();
    return hd;
  };
  T._renderPaper = renderPaper; T._renderLive = renderLive;
