  // ======================================================================
  // JOURNAL · trade log of archived strategies + closed legs (stats, equity curve, tags, notes, CSV)
  // ======================================================================
  const JTAGS = ['earnings', 'range', 'hedge'];
  const JFILTERS = ['All', 'Paper', 'Live', 'Wins', 'Losses'];
  function jRows() { const q = S.jSearch.trim().toLowerCase(); let rows = M.strategies.filter((s) => s.status === 'ARCHIVED'); rows.forEach(recalc); const f = S.jFilter; if (f === 'Paper') rows = rows.filter((s) => s.tradingMode === 'PAPER'); else if (f === 'Live') rows = rows.filter((s) => s.tradingMode === 'LIVE'); else if (f === 'Wins') rows = rows.filter((s) => s.totalPnl > 0); else if (f === 'Losses') rows = rows.filter((s) => s.totalPnl < 0); else if (CG.ASSETS[f]) rows = rows.filter((s) => s.asset === f); if (q) rows = rows.filter((s) => s.name.toLowerCase().includes(q) || (s.templateName || '').toLowerCase().includes(q) || s.asset.toLowerCase().includes(q) || (s.tags || []).some((t) => t.includes(q)) || (s.notes || '').toLowerCase().includes(q)); return rows.sort((a, b) => new Date(b.closedAt || b.createdAt) - new Date(a.closedAt || a.createdAt)); }
  function jClosedLegs() { const out = []; M.strategies.filter((s) => s.status === 'PAPER' || s.status === 'LIVE').forEach((s) => s.legs.forEach((l) => { if (l.status !== 'SQUARED_OFF') return; const p = legPnl(l, s.asset); out.push({ s, l, pnl: p.pnl, entry: p.entry, exit: p.current, closedAt: l.closedAt || s.updatedAt || s.startedAt || s.createdAt }); })); return out.sort((a, b) => new Date(b.closedAt) - new Date(a.closedAt)); }
  function jStats(rows) { const n = rows.length; const pnls = rows.map((s) => s.totalPnl); const wins = pnls.filter((p) => p > 0); const losses = pnls.filter((p) => p < 0); const gp = wins.reduce((a, b) => a + b, 0), gl = Math.abs(losses.reduce((a, b) => a + b, 0)); return { n, wins: wins.length, losses: losses.length, winRate: n ? wins.length / n : null, avg: n ? pnls.reduce((a, b) => a + b, 0) / n : null, best: n ? Math.max(...pnls) : null, worst: n ? Math.min(...pnls) : null, pf: gl > 0 ? gp / gl : (gp > 0 ? Infinity : null), total: pnls.reduce((a, b) => a + b, 0) }; }
  function equityCurve(rows) {
    const sorted = rows.slice().sort((a, b) => new Date(a.closedAt || a.createdAt) - new Date(b.closedAt || b.createdAt)); if (!sorted.length) return '';
    const first = sorted[0]; const pts = [{ t: new Date(first.startedAt || first.createdAt).getTime(), v: 0 }]; let cum = 0; sorted.forEach((s) => { cum += s.totalPnl; pts.push({ t: new Date(s.closedAt || s.createdAt).getTime(), v: +cum.toFixed(2), s }); });
    const W = 600, H = 120, mL = 46, mR = 14, mT = 12, mB = 18; const t0 = pts[0].t, t1 = Math.max(pts[pts.length - 1].t, t0 + 1); const vs = pts.map((p) => p.v); const min = Math.min(0, ...vs), max = Math.max(0, ...vs); const rng = (max - min) || 1;
    const X = (t) => +(mL + (W - mL - mR) * (t - t0) / (t1 - t0)).toFixed(1); const Y = (v) => +(mT + (H - mT - mB) * (1 - (v - min) / rng)).toFixed(1);
    let s = '<svg viewBox="0 0 ' + W + ' ' + H + '" role="img" aria-label="Equity curve · cumulative realised P&L">';
    const ticks = Array.from(new Set([min, (min + max) / 2, max].map((v) => +v.toFixed(2))));
    ticks.forEach((v) => { s += '<line x1="' + mL + '" x2="' + (W - mR) + '" y1="' + Y(v) + '" y2="' + Y(v) + '" stroke="hsl(var(--border))"/><text x="' + (mL - 6) + '" y="' + (Y(v) + 3) + '" text-anchor="end">' + smoney(v, 0) + '</text>'; });
    s += '<line x1="' + mL + '" x2="' + (W - mR) + '" y1="' + Y(0) + '" y2="' + Y(0) + '" stroke="hsl(var(--muted-foreground))" stroke-dasharray="2 3"/>';
    const d = pts.map((p, i) => (i ? 'L' : 'M') + X(p.t) + ' ' + Y(p.v)).join(' '); const last = pts[pts.length - 1]; const c = last.v >= 0 ? 'hsl(var(--profit))' : 'hsl(var(--loss))';
    s += '<path d="' + d + ' L' + X(last.t) + ' ' + Y(0) + ' L' + X(pts[0].t) + ' ' + Y(0) + ' Z" fill="' + c + '" opacity=".12"/><path d="' + d + '" fill="none" stroke="' + c + '" stroke-width="1.6" stroke-linejoin="round"/>';
    pts.slice(1).forEach((p) => { s += '<circle cx="' + X(p.t) + '" cy="' + Y(p.v) + '" r="2.4" fill="hsl(var(--card))" stroke="' + c + '" stroke-width="1.2"><title>' + esc(p.s.name) + ' · ' + smoney(p.s.totalPnl) + ' · ' + fmtDate(p.s.closedAt || p.s.createdAt) + '</title></circle>'; });
    s += '<circle cx="' + X(last.t) + '" cy="' + Y(last.v) + '" r="3.5" fill="' + c + '"/><text x="' + (X(last.t) - 8) + '" y="' + (Y(last.v) - 7 < mT + 8 ? Math.min(H - mB - 4, Y(last.v) + 14) : Y(last.v) - 7) + '" text-anchor="end" fill="' + c + '" font-weight="500">' + smoney(last.v) + '</text>';
    s += '<text x="' + mL + '" y="' + (H - 4) + '">' + fmtShort(pts[0].t) + '</text><text x="' + (W - mR) + '" y="' + (H - 4) + '" text-anchor="end">' + fmtShort(last.t) + '</text>';
    return s + '</svg>';
  }
  function jRow(s) {
    const tags = s.tags || []; const custom = tags.filter((t) => !JTAGS.includes(t)); const d = daysOf(s); const closed = s.closedAt || s.createdAt;
    return '<div class="trd-jrow" data-id="' + s.id + '"><div class="trd-jrow-main" data-act="j-open" title="Open strategy details"><div class="trd-jrow-date"><b>' + fmtShort(closed) + '</b>' + new Date(closed).getFullYear() + '</div><div style="min-width:0"><div class="trd-jrow-name">' + esc(s.name) + (s.tradingMode ? '<span class="trd-mode-pill arch">' + (s.tradingMode === 'LIVE' ? 'live' : 'paper') + '</span>' : '') + '<span class="trd-tag">' + s.asset + '</span></div><div class="trd-jrow-meta">' + (s.templateName ? '<span>' + esc(s.templateName) + '</span>' : '') + '<span><b>' + s.legs.length + '</b> legs</span><span><b>' + d + '</b> days</span><span>' + fmtShort(s.startedAt || s.createdAt) + ' → ' + fmtShort(closed) + '</span>' + (tags.length ? '<span>' + tags.map((t) => '#' + esc(t)).join(' ') + '</span>' : '') + '</div></div><div class="trd-jrow-pnl ' + pnlClass(s.totalPnl) + '">' + smoney(s.totalPnl) + '<small>realised</small></div></div>' +
      '<div class="trd-jrow-edit"><div><span class="micro">Tags</span><div class="trd-tags">' + JTAGS.map((t) => '<button class="trd-tagc' + (tags.includes(t) ? ' on' : '') + '" data-act="j-tag" data-tag="' + t + '" title="Toggle tag">' + t + '</button>').join('') + custom.map((t) => '<button class="trd-tagc on" data-act="j-tag" data-tag="' + esc(t) + '" title="Remove tag">' + esc(t) + '<span class="x">×</span></button>').join('') + '<input class="trd-tagin" data-act="j-tag-in" placeholder="+ custom" maxlength="24" aria-label="Add a custom tag (Enter)"></div></div><div><span class="micro">Notes</span><textarea class="trd-notes" data-act="j-notes" placeholder="What worked, what did not…" rows="2">' + esc(s.notes || '') + '</textarea></div></div></div>';
  }
  function jLeg(x) { return '<div class="trd-jleg" data-act="j-open-s" data-id="' + x.s.id + '" title="Open ' + esc(x.s.name) + '"><span class="dim">' + fmtShort(x.closedAt) + '</span>' + sideBadge(x.l.side) + '<span class="truncate"><b style="font-weight:500">' + esc(x.l.symbol) + '</b> <span class="dim">· ' + esc(x.s.name) + ' · ' + x.l.lots + ' lots</span></span><span class="r dim">' + F.num(x.entry, 1) + ' → ' + F.num(x.exit, 1) + '</span><span class="r ' + pnlClass(x.pnl) + '">' + smoney(x.pnl) + '</span></div>'; }
  function csvOf(rows) { const cols = ['id', 'name', 'mode', 'asset', 'template', 'legs', 'opened', 'closed', 'days', 'realized_pnl', 'tags', 'notes']; const q = (v) => { v = v == null ? '' : String(v); return /[",\n]/.test(v) ? '"' + v.replace(/"/g, '""') + '"' : v; }; const lines = [cols.join(',')]; rows.forEach((s) => lines.push([s.id, s.name, s.tradingMode || '', s.asset, s.templateName || '', s.legs.length, (s.startedAt || s.createdAt || '').slice(0, 10), (s.closedAt || '').slice(0, 10), daysOf(s), s.totalPnl.toFixed(2), (s.tags || []).join('|'), s.notes || ''].map(q).join(','))); return lines.join('\n'); }
  function copyText(text) { const fallback = () => { try { const ta = document.createElement('textarea'); ta.value = text; ta.setAttribute('readonly', ''); ta.style.position = 'fixed'; ta.style.opacity = '0'; document.body.appendChild(ta); ta.select(); const ok = document.execCommand('copy'); ta.remove(); return ok; } catch (e) { return false; } }; return new Promise((res) => { if (navigator.clipboard && navigator.clipboard.writeText) navigator.clipboard.writeText(text).then(() => res(true), () => res(fallback())); else res(fallback()); }); }
  T.journalCsv = () => csvOf(jRows());
  function renderJournal() {
    const el = S.els.journal; if (!el) return; const rows = jRows(); const all = M.strategies.filter((s) => s.status === 'ARCHIVED'); const st = jStats(rows); const legs = jClosedLegs();
    const chips = JFILTERS.concat(Object.keys(CG.ASSETS));
    let html = '<div class="trd-toolbar"><div class="trd-chips">' + chips.map((c) => '<button class="trd-chip' + (S.jFilter === c ? ' active' : '') + '" data-act="j-filter" data-f="' + c + '">' + c + '</button>').join('') + '</div>' + searchBox('Search trades, tags, notes...', S.jSearch, 'j-search') + '<button class="btn btn-outline btn-sm" data-act="j-export" title="Copy the filtered trades as CSV">' + I.copy + ' Export CSV</button></div>';
    const cell = (k, v, sub, cls) => '<div><span class="micro">' + k + '</span><div class="v ' + (cls || '') + '">' + v + '</div><div class="s">' + sub + '</div></div>';
    html += '<div class="trd-jstats">' + cell('Trades', st.n, plural(st.wins, 'win') + ' · ' + plural(st.losses, 'loss').replace('losss', 'losses')) + cell('Win rate', st.winRate == null ? '—' : Math.round(st.winRate * 100) + '%', 'closed strategies') + cell('Avg P&amp;L', st.avg == null ? '—' : smoney(st.avg), 'per trade', st.avg == null ? '' : pnlClass(st.avg)) + cell('Best', st.best == null ? '—' : smoney(st.best), 'single trade', st.best == null ? '' : pnlClass(st.best)) + cell('Worst', st.worst == null ? '—' : smoney(st.worst), 'single trade', st.worst == null ? '' : pnlClass(st.worst)) + cell('Profit factor', st.pf == null ? '—' : st.pf === Infinity ? '∞' : st.pf.toFixed(2), 'gross profit ÷ gross loss') + '</div>';
    if (!all.length && !legs.length) html += '<div class="empty" style="padding:44px 16px"><div class="trd-empty-ico">' + I.book + '</div><b>No closed trades yet</b>Archived strategies and squared-off legs appear here with tags, notes and an equity curve.<div class="mt-3"><button class="btn btn-outline btn-sm" data-act="j-goto-paper">Open Paper trades</button></div></div>';
    else {
      html += '<div class="trd-curve"><div class="flex items-center gap-2 mb-1"><span class="micro">Equity curve</span><span class="micro">·</span><span class="micro">cumulative realised P&amp;L · ' + plural(rows.length, 'trade') + '</span><span class="micro" style="margin-left:auto">net <b class="' + pnlClass(st.total) + '">' + smoney(st.total) + '</b></span></div>' + (rows.length ? equityCurve(rows) : '<div class="empty" style="padding:14px">No trades match this filter</div>') + '</div>';
      html += '<div class="trd-body">' + (rows.length ? '<div class="trd-list">' + rows.map(jRow).join('') + '</div>' : (all.length ? '<div class="empty"><b>No matching trades</b>Try another filter or search</div>' : '<div class="empty"><b>No archived strategies yet</b>Stop or square off a strategy to log it here</div>'));
      if (legs.length) html += '<div class="trd-sec"><span class="micro">Closed legs from active strategies</span><span class="micro">' + legs.length + '</span></div><div class="trd-jlegs">' + legs.map(jLeg).join('') + '</div>';
      html += '</div>';
    }
    el.innerHTML = html;
  }
  function bindJournal() {
    const el = S.els.journal;
    CG.delegate(el, 'click', '[data-act]', (e, t) => {
      const act = t.dataset.act; const row = t.closest('[data-id]'); const s = row ? byId(row.dataset.id) : null;
      if (act === 'j-filter') { S.jFilter = t.dataset.f; renderJournal(); }
      else if (act === 'j-search-clear') { S.jSearch = ''; renderJournal(); }
      else if (act === 'j-export') { const rows = jRows(); if (!rows.length) return CG.toast({ title: 'Nothing to export', description: 'No trades match the current filter' }); const csv = csvOf(rows); T.lastCsv = csv; copyText(csv).then((ok) => CG.toast({ title: 'CSV copied · ' + plural(rows.length, 'row'), description: ok ? 'Paste into a spreadsheet' : 'Clipboard blocked by the browser · CSV kept in CG.trading.lastCsv', variant: 'success' })); }
      else if (act === 'j-goto-paper') CG.emit('analyse:set-tab', 'paper');
      else if ((act === 'j-open' || act === 'j-open-s') && s) T.openDetails(s.id);
      else if (act === 'j-tag' && s) { const tag = t.dataset.tag; s.tags = s.tags || []; const i = s.tags.indexOf(tag); if (i >= 0) s.tags.splice(i, 1); else s.tags.push(tag); s.updatedAt = nowIso(); renderJournal(); CG.toast({ title: i >= 0 ? 'Tag removed' : 'Tag added', description: '#' + tag + ' · ' + s.name }); }
    });
    el.addEventListener('keydown', (e) => { const t = e.target; if (t.dataset && t.dataset.act === 'j-tag-in' && e.key === 'Enter') { e.preventDefault(); const row = t.closest('[data-id]'); const s = row && byId(row.dataset.id); const v = t.value.trim().toLowerCase().replace(/[^a-z0-9\-_ ]/g, '').slice(0, 24); if (!s || !v) return; s.tags = s.tags || []; if (!s.tags.includes(v)) s.tags.push(v); s.updatedAt = nowIso(); renderJournal(); CG.toast({ title: 'Tag added', description: '#' + v + ' · ' + s.name }); } });
    el.addEventListener('input', (e) => { const t = e.target; if (t.dataset.act === 'j-search') { S.jSearch = t.value; const pos = t.selectionStart; renderJournal(); const n = el.querySelector('[data-act="j-search"]'); if (n) { n.focus(); n.setSelectionRange(pos, pos); } } else if (t.dataset.act === 'j-notes') { const row = t.closest('[data-id]'); const s = row && byId(row.dataset.id); if (s) { s.notes = t.value; s.notesDirty = true; } } });
    el.addEventListener('change', (e) => { const t = e.target; if (t.dataset.act === 'j-notes') { const row = t.closest('[data-id]'); const s = row && byId(row.dataset.id); if (s && s.notesDirty) { s.notesDirty = false; s.updatedAt = nowIso(); CG.toast({ title: 'Notes saved', description: s.name }); } } });
  }
  T.renderJournal = renderJournal;
  T._renderJournal = function () { if (S.panels.journal && !S.panels.journal.hidden) renderJournal(); };
